### ISSUE TITLE
Settings schema 'de.haecker-felix.gradio' is not installed

### ISSUE THREAD

**Issue by actionless** [haecker-felix/gradio#102]
In AUR I've tried both `gradio` and `gradio-git` and I have the same message when attempting to start:

```
(gradio:18366): GLib-GIO-ERROR **: Settings schema 'de.haecker-felix.gradio' is not installed

Trace/breakpoint trap (core dumped)
```

```bash
$ pacman -Ql gradio | grep gschema
gradio /usr/local/share/glib-2.0/schemas/de.haecker-felix.gradio.gschema.xml
```

Previous release was working fine for me.

**Comment by actionless** [comment]
it was a problem with package itself https://aur.archlinux.org/cgit/aur.git/tree/gradio.install?h=gradio

**Comment by dw72** [comment]
is this problem corrected? Because when I try to run it:
```
(gradio:12149): GLib-GIO-ERROR **: Settings schema 'de.haecker-felix.gradio' is not installed
```

**Comment by actionless** [comment]
@dw72 see my AUR comment on how to fix it
