### ISSUE TITLE
Symbolic icon for dark tray

### ISSUE THREAD

**Issue by dw72** [haecker-felix/gradio#103]
Can you add symbolic icon with light color for dark toolbars?

**Comment by haecker-felix** [comment]
Which specific icon do you mean?

**Comment by dw72** [comment]
As you can see on screenshot:
![zrzut ekranu z 2016-11-17 08-06-51](https://cloud.githubusercontent.com/assets/1017175/20379556/2d7ec4ee-ac9d-11e6-87f5-16ac0c1e3b85.png)
I tried change this icon adding light variant in icon theme but without success.

BTW it will be good to have menu after right click this icon, with 'Quit' an maybe some other otpions.
