### ISSUE TITLE
Feature request: Export/import library

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#104]
**Issue:**
There is no way to export the library and import it after a fresh install. After each new fresh install you have to start building your library from scratch. 

**Feature requested:**
Allow the user to export the library and import it. Two new entries in the menu like `Import library` and `Export library` would be enough.

**Implementation:**
I think the easiest solution would be to make a copy of `.local/share/gradio/library.gradio` while exporting and override it while importing.

**Comment by grindhold** [comment]
why would you need an extra feature for that? you can just copy the library onto the new installation :/
packagemangagers like apt in debian even go as far as keeping configfiles, in case the user decides to reinstall the application (unless you purge everything).

**Comment by mohamedsakhri** [comment]
> why would you need an extra feature for that? you can just copy the library onto the new installation :/

I did that, but I don't think a regular user is supposed to know how to do that.

> packagemangagers like apt in debian even go as far as keeping configfiles, in case the user decides to reinstall the application (unless you purge everything).

A fresh install can also take place on another system or computer. In this case there will be no config files. Gradio has no profiling or synchronization option to synchronize the library. That's why I think it would make sense to have at least an Export/Import library feature.

**Comment by haecker-felix** [comment]
I can add this feature. This is no problem. You dont have to use it, if you don't want it 😃.

I'm sorry but i can't develop gradio currently, because i have strange problems with my new setup. (Fedora + Nvidia Gtx 1060, Windows is working fine 😟). I'm working on a solution. Just as information. Gradio is _not_ dead.

**Comment by grindhold** [comment]
hmmm. brings me to the idea that in the long term a central gnome-backup-my-applications-tool would make sense. in my opinion, having a import/export feature in each application violates unix philosophy. But you're right. UI-centric users are not necessarily fond of copying dotfolders.

**Comment by mohamedsakhri** [comment]
@haecker-felix Welcome back :tada: 

@grindhold I consider the library as bookmarks in web browsers. They can be synchronised or/and exported/imported.
