### ISSUE TITLE
No icon when running on Xfce

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#105]
When running gradio on Xfce the windows lacks an icon and only a generic icon is used
![bildschirmfoto_2016-11-19_22-10-24](https://cloud.githubusercontent.com/assets/1418818/20458421/268e3228-aea5-11e6-8eff-1f5b3dafe38d.png)

**Comment by mohamedsakhri** [comment]
I'm using XFCE and the gradio icon is displayed fine :thinking:

**Comment by billypilgrim-uk** [comment]
I'm running Gradio on Xfce (Manjaro 16.10.1 Fringilla) and I don't get any icon at all in my tray (generic or otherwise) though it still runs in the background...

**Comment by HeikoAdams** [comment]
@mohamedsakhri what icon-theme are you using?

**Comment by mohamedsakhri** [comment]
I'm using [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk)

**Comment by HeikoAdams** [comment]
Maybe that icon-theme has an icon for gradio but I'm using Fedora's default icon theme and there is **no** icon - in that case gradio should have a fallback icon

**Comment by mohamedsakhri** [comment]
Even with Adwaita and the GNOME default icons set there is an icon on my system, a different one than the one from Papirus.. 
A fallback icon from gradio should be provided anyway. I'm not sure if it is provided and there is an issue displaying it on some configurations or there is none.

**Comment by haecker-felix** [comment]
Should be fixed now. Make sure you the icons are correctly installed ("# make install" should do it, or install gradio as a package)
