### ISSUE TITLE
Sortable library

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#106]
It seems the library is randomly sorted but it would be nice if the library could be sorted by name of the staton

**Comment by mohamedsakhri** [comment]
The library is sorted according to the way GLib.HashMap sorts its entries. I'm also for this feature. A sorted library would be nice :+1:

**Comment by cunei** [comment]
It would be even better to be able to reorder stations by drag and drop. Sometimes you want to group stations according to some personal preference, rather than by name.

**Comment by haecker-felix** [comment]
I'm working on a new "Collections" Feature. This is like folders. You can add several stations to a collection/folder/group. I'm still thinking over it. A drag'n drop feature would be very hard to implement.

**Comment by haecker-felix** [comment]
Progress update:

![searchfilter](https://user-images.githubusercontent.com/6001248/27256043-138b3b20-53ab-11e7-9ede-6392a5e3cc5b.png)
![collection](https://user-images.githubusercontent.com/6001248/27256044-169eaa5e-53ab-11e7-8b5a-b39e9fe7f555.png)

- The library can now be sorted into "collections". 
- The search results are completely sortable

Missing:
- Completely sortable library (like in search)

**Comment by haecker-felix** [comment]
*Every* radio station page is now sortable!

Finally I can close this bug ^^.

**Comment by arooni** [comment]
I was just looking for this!  I assume this hasn't been released in 5.0 yet right?

**Comment by haecker-felix** [comment]
@arooni no unfortunately not. Will land in 6.0.

**Comment by AinaSG** [comment]
Ow! I worked on this for a while but I was not happy with the results. It looks amazing! 
Thanks for developing Gradio!
