### ISSUE TITLE
Searched-for stations not playable

### ISSUE THREAD

**Issue by billypilgrim-uk** [haecker-felix/gradio#108]
Hi, I'm running gradio in Arch Linux via the gradio-git package in the aur. A station will play correctly (and can be favourited etc.) if I click on it in the discover tab, but if I try searching for it by name the entries in the search list seem not to be playable. I've tried clicking, double-clicking, clicking on the star (for favouriting) next to the station but nothing seems to work.

**Comment by haecker-felix** [comment]
Try the latest commit.
