### ISSUE TITLE
Gradio doesn't minimize to tray if no station has been played

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#109]
**User case:**
1. Open Gradio ( Minimize to tray icon is enabled)
2. Close the window before starting any station
3. Gradio closes instead of minimizing to tray

Only if you have started a station first you can minimize the window after that.

**Comment by haecker-felix** [comment]
This should be a feature :D.

Why I need background playing when no song is playing?

**Comment by mohamedsakhri** [comment]
> This should be a feature :D.

:D 
I think it is confusing because the behaviour of the same action (close) is inconsistent. 

> Why I need background playing when no song is playing?

Because of the consistency of the feature "minimize to tray". Another reason is to be able to restore the window with a click rather to start it again. Than can be useful if the user need to stop a station for a short time.
We've also discussed the feature about right click on the tray icon to "play/stop" and "quit". Without background playing it won't be possible..

**Comment by haecker-felix** [comment]
![gradio_settings](https://cloud.githubusercontent.com/assets/6001248/20647079/f8e1ca38-b48a-11e6-84c9-1a05777268ce.png)

I agree, but than i have to change the label. Because "Continue playback in background" is only active, if there is a active playback.

**Comment by mohamedsakhri** [comment]
Yes, I also think so. What do you think about this structure? 

- Window preferences
   - Minimize to tray when closing main window
- Notifications
   - Show notifications
- Playback preferences
   - Resume playback on start-up
   - Enable background playback
- Appearance
   - Use dark theme

In some categories, e.g Notifications, more features can be added in the future..
