### ISSUE TITLE
Make "minimize to tray" to "close to tray"

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#110]
When running gradio (latest git master) on Xfce 4.12 there is no trayicon even if "minimize to tray" option is activated

![bildschirmfoto_2016-11-27_11-20-41](https://cloud.githubusercontent.com/assets/1418818/20647388/9220b896-b493-11e6-93c5-ed155e06b867.png)

After restarting gradio and minimizing gradio my desktop looks like this
![bildschirmfoto_2016-11-27_11-19-04](https://cloud.githubusercontent.com/assets/1418818/20647389/951aaa02-b493-11e6-8ea4-99abb3da3d90.png)
No trayicon and gradio's window icon is still visible on the panel

**Comment by mohamedsakhri** [comment]
Is this the same issue as https://github.com/haecker-felix/gradio/issues/109 ?

**Comment by HeikoAdams** [comment]
No, because in my case the tray icon doen't work generaly

**Comment by HeikoAdams** [comment]
Okay, minimize to tray works. But only if I click on the **close** instead of the **minimize** button in the titlebar 🤔
