### ISSUE TITLE
Use dark theme when gtk-application-prefer-dark-theme=1

### ISSUE THREAD

**Issue by PlusMinus0** [haecker-felix/gradio#112]
Gradio should initially use the dark theme when

 `gtk-application-prefer-dark-theme=1`

is set in `~/.config/gtk-3.0/settings.ini.`

Ideally there should be three options for the theme setting: Force bright, Force dark, system default.

**Comment by haecker-felix** [comment]
Gradio respects these settings. Cannot reproduce this behavior on fedora 25. Just open the settings and enable dark design.
