### ISSUE TITLE
Right click menu behaviour

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#113]
Currently, right click menu can be activated  simultaneously for each radio station in library / discover mode :

![screenshot from 2016-11-30 20-07-42](https://cloud.githubusercontent.com/assets/296922/20784093/5f0e8f20-b798-11e6-9e1b-adaca6667cea.png)

Maybe right click menu could be activated only once at time , then if right click  menu is already active, when you choose it for another radio station, previous one will be closed in automated way...

Thanks
Andrea

**Comment by haecker-felix** [comment]
a new right click behavior is now in master.
