### ISSUE TITLE
Gradio crashes whenever a station is clicked (Segmentation fault)

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#114]
A segmentation fault crash is caused whenever I click a station. This is the output of running Gradio from the terminal:

> ** Message: gradio.vala:172: >> Starting Gradio version 4.9.9 <<
> ** Message: gradio.vala:36: No existing window, starting new session.
> ** Message: settings.vala:24: Loaded settings module
> ** Message: library.vala:110: Reading library data from: .local/share/gradio/library.gradio
> ** Message: station-registry.vala:35: [1] "NDR Plus" is registered. (1 active stations)
> ** Message: library.vala:135: Successfully imported library data
> ** Message: main-window.vala:79: Desktop session is xfce.
> ** Message: category-item-provider.vala:36: Fetching category items...
> 
> (gradio:3066): Gtk-WARNING **: Could not find signal handler 'OpenHomepageButton_clicked'.  Did you compile with -rdynamic?
> 
> (gradio:3066): Gtk-WARNING **: Could not find signal handler 'VolumeButton_value_changed'.  Did you compile with -rdynamic?
> 
> (gradio:3066): Gtk-WARNING **: Could not find signal handler 'LikeButton_clicked'.  Did you compile with -rdynamic?
> 
> (gradio:3066): Gtk-WARNING **: Could not find signal handler 'AddRemoveButton_clicked'.  Did you compile with -rdynamic?
> 
> (gradio:3066): Gtk-WARNING **: Could not find signal handler 'PlayStopButton_clicked'.  Did you compile with -rdynamic?
> ** Message: utils.vala:96: Loaded CSS from: /usr/local/share/gradio/gradio.css
> ** Message: category-item-provider.vala:127: Successfully loaded category items!
> ** Message: discover-box-sidebar.vala:139: Loading category items...
> ** Message: station-registry.vala:35: [16] "Flux FM (320k)" is registered. (16 active stations)
> ** Message: station-registry.vala:35: [17] "Energy Urban" is registered. (17 active stations)
> ** Message: station-registry.vala:35: [18] "Energy Stuttgart" is registered. (18 active stations)
> ** Message: station-registry.vala:35: [19] "Energy Sachsen" is registered. (19 active stations)
> ** Message: station-registry.vala:35: [20] "Energy Romantic" is registered. (20 active stations)
> ** Message: station-registry.vala:35: [21] "Energy Rock" is registered. (21 active stations)
> ** Message: station-registry.vala:35: [22] "Energy RnB" is registered. (22 active stations)
> ** Message: station-registry.vala:35: [23] "Energy Relax" is registered. (23 active stations)
> ** Message: station-registry.vala:35: [24] "Energy Rap US" is registered. (24 active stations)
> ** Message: station-registry.vala:35: [25] "Energy Party Hits" is registered. (25 active stations)
> ** Message: station-registry.vala:35: [26] "Energy Oriental" is registered. (26 active stations)
> ** Message: station-registry.vala:35: [27] "Energy Nürnberg 106,9" is registered. (27 active stations)
> ** Message: station-registry.vala:35: [28] "Energy München 93,3" is registered. (28 active stations)
> ** Message: station-registry.vala:35: [29] "Energy Metal" is registered. (29 active stations)
> ** Message: station-registry.vala:35: [30] "Energy Mastermix" is registered. (30 active stations)
> ** Message: station-registry.vala:35: [31] "Energy Love" is registered. (31 active stations)
> ** Message: station-registry.vala:35: [32] "Energy Lounge" is registered. (32 active stations)
> ** Message: station-registry.vala:35: [33] "Energy Latino" is registered. (33 active stations)
> ** Message: station-registry.vala:35: [34] "CKBN" is registered. (34 active stations)
> ** Message: station-registry.vala:35: [35] "95bFM" is registered. (35 active stations)
> Segmentation fault
> 

After some debugging I figured out the bug is caused by 3efe45f9bcd0a0f5a2e823dde28e9efeb696e16c and exactly by the method call `tag_changed(); `. Removing it fixed the bug.

**Comment by cortopy** [comment]
experiencing same issue on Fedora 24 after upgrading gradio to `5.0-0.2.201612022030git1944795.fc24 `

**Comment by haecker-felix** [comment]
The problem is, without the line "tag_changed();" bug #111 occurs. Second problem is, this does _not_ occurs on my system, so its a bit hard to "fix" it. Third problem, i'm a bit busy at the moment.

Which Gradio settings do you use?

@cortopy do you have fedora 25 to test?

**Comment by cortopy** [comment]
@haecker-felix I should be upgrading soon, but installing the latest 0.2.201612092230git8b44995.fc24 (from coper repo) does the trick. Thanks a lot!!
