### ISSUE TITLE
Settings dialog improvements

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#117]
After a23ba6e2e9acdc03e5c3f9ce576562c06873bbfd and 5651b965260d863a6e2195012a87d62d945549ed the settings window has been modified. Here are some thoughts and suggestions about the changes and the settings window in general:

1. I think the old design was better than the design of the actual tabs. The same design as the tabs "discover" and "library" looks modern.
2. The message "Some settings need a restart of Gradio" can be implemented otherwise. It would be better if a message "Your changes will be applied after the next restart of Gradio" pops up only when the user changes a setting that needs a restart.

**Comment by haecker-felix** [comment]
You're right. 
1. I know, but the actual solution is more developer friendly and easier to maintenance. I'm trying to find a ideal mix.
2. Or completely remove the "need a restart" and apply the changes immediately :D

**Comment by haecker-felix** [comment]
I'm using a settings "page" now. I think it is much easier to use.
