### ISSUE TITLE
gradio - 5.0.0+r333-0~ubuntu16.04.1 install from PPA doesn't

### ISSUE THREAD

**Issue by edgarde** [haecker-felix/gradio#121]
Upgraded from PPA using Synaptic version 4.0.1 (as I recall) to 5.0.0+r331-0~ubuntu16.04.1. Here is what remains under Installed Files:

/usr
/usr/share
/usr/share/doc
/usr/share/gradio
/usr/share/gradio/changelog.Debian.gz
/usr/share/gradio/copyright

~.local/share/gradio/library.gradio also remains.

Looks like it uninstalled without re-installing. I'm noticing on https://launchpad.net/~haecker-felix/+archive/ubuntu/gradio-daily it currently says latest updates failed to build. 

Me: Linux Mint 18 'Sarah' "Cinnamon 64-bit"

`# uname -a`
Linux notmyname 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`# less /proc/version`
Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016

**Comment by Seebz** [comment]
Same issue for me

**Comment by haecker-felix** [comment]
Yes there are actually some strange problems with the packaging, because I switched from cmake to automake. I'm working on a solution.

**Comment by haecker-felix** [comment]
New package is out. The problems should be gone now.

**Comment by Seebz** [comment]
I confirm it works now. Thank you for all your work

**Comment by edgarde** [comment]
Working for me as well. Thanks!

**Comment by gungoksu** [comment]
installed on 16.10 Ubuntu Yakketi Yak Xfce from PPA with no problems.
