### ISSUE TITLE
Error or bug?

### ISSUE THREAD

**Issue by csola48** [haecker-felix/gradio#122]
**GRadio 5.0.0.**

A szükséges bővítmény nem található
A(z) Gradio további bővítmények telepítését igényli a  következő fájltípus lejátszásához: 
text/uri-list decoder

**Comment by csola48** [comment]
What is MIME text/uri-list ?! 
http://bit.ly/2itBSDJ

**Comment by csola48** [comment]
![kepmentes_042](https://cloud.githubusercontent.com/assets/893186/21471691/7e78d5ca-caba-11e6-8dea-c364e1fea960.png)

**Comment by haecker-felix** [comment]
It's not a bug of gradio itself. The database (radio-browser.info) returns the wrong playable address. I've already reported this to the developer.
