### ISSUE TITLE
Left menu open up on the right transparent

### ISSUE THREAD

**Issue by armageddon51** [haecker-felix/gradio#125]
Great upgrade thanks ! One annoying feature, the left menu items open up on the right side and transparent but on top of the stations (discover). Very hard to read the selections.

Thanks

**Comment by VosaXalo** [comment]
I confirm this behavior, at least on Ubuntu Unity 16.04 LTS. This is very hard to read. 
I think that adding a background to the left menu will resolve this issue.

**Comment by lmaze** [comment]
I also confirm this bug in Ubuntu 16.04. I have a default installation with the standard theme.

![bug gradio](https://cloud.githubusercontent.com/assets/11060691/21583669/90568af4-d08b-11e6-9520-12d1774c3499.jpg)

**Comment by haecker-felix** [comment]
Yes there are some design (css) problems with the ubuntu default theme. I'll fix it.

**Comment by bentolor** [comment]
> Try the gtk default design, and it works like a charm.

How to achieve that? Ticking/Unticking "Use dark design" has no visible effect.

**Comment by jcolladoa** [comment]
I also confirm this issue in Ubuntu 16.04.  And I don't know how to switch to gtk default design, as Felix noticed. Any suggestion or workaround in the meanwhile?

**Comment by k-andreas** [comment]
I can confirm this issue in Ubuntu 16.10 running version 5.0.12+r344-0~ubuntu16.10.1 . 

How can I switch to the gtk default design?

**Comment by haecker-felix** [comment]
Fixed.
