### ISSUE TITLE
Searchable lists (languages, countries, etc.)

### ISSUE THREAD

**Issue by marcelopm** [haecker-felix/gradio#128]
I would like to suggest adding quickfilter/autocomplete to all lists (langs, countries, tags, states, etc). Something similar to jQuery UI autocomplete widget: https://jqueryui.com/autocomplete/#combobox

Cheers

**Comment by haecker-felix** [comment]
To which list? There is only one entry, and this is the search entry. What should be auto completed?

If you mean the search entry: I'm working on it.

**Comment by marcelopm** [comment]
I mean the lists available on the sidebar:

![screenshot from 2016-12-30 10-09-50](https://cloud.githubusercontent.com/assets/1010930/21557460/2f97dd04-ce78-11e6-8dae-611f3d8e7cd6.png)

If the jQuery example doesn't make sense, maybe something like this:

![Image of list](https://people.gnome.org/~carlosg/popover-normal.png)
ref: https://blogs.gnome.org/mclasen/2014/01/22/and-now-popovers/

Cheers

**Comment by haecker-felix** [comment]
Ah you mean a searchable list of languages, states, etc.

The next version of gradio will contain a more powerful search.

**Comment by marcelopm** [comment]
:thumbsup:  :clap: :clap: :clap:

**Comment by haecker-felix** [comment]
Gradio has now a more powerful search engine. Just landed in master!
