### ISSUE TITLE
Regression: Window resize down to 1024px width no longer possible

### ISSUE THREAD

**Issue by stroobandt** [haecker-felix/gradio#129]
With the latest upgrade of gradio, I can no longer resize the application window to 1024px width or smaller.
(I actually need a width of maximum 996px.)
The width of the station buttons seem to block things off.
Consider a flexible design (like modern HTML pages), either by automatically switching to two column layout or by wrapping or trunkating any button overflow.

**Comment by haecker-felix** [comment]
Yes the actual discover design is very problematic. I'm going to re-design the discover page a bit, to make the design more flexible.

**Comment by haecker-felix** [comment]
Gradio has a new layout now. It is much more resizeable.
