### ISSUE TITLE
Open with MPRIS notification is wrong

### ISSUE THREAD

**Issue by simonbcn** [haecker-felix/gradio#131]
_I don't know how to title this issue. My english isn't good._ 

```
Arch Linux 64 bits
gradio-git installed from AUR package 
GNOME Shell 3.22.2 with Wayland
```
My options:
![opciones](https://cloud.githubusercontent.com/assets/428231/21607563/4ce9b46c-d1b7-11e6-84c8-d053565f4b0b.jpg)

When I start gradio:
![primera](https://cloud.githubusercontent.com/assets/428231/21607611/a11e4a0c-d1b7-11e6-8bf2-292ea979a8e3.jpg)

When I close the window the tray icon isn't showed ( #126 and #96 ) so I click on MPRIS notification to open the gradio window again but:
![segunda](https://cloud.githubusercontent.com/assets/428231/21607629/c2cc97d0-d1b7-11e6-9eab-860738a1453e.jpg)

**Comment by haecker-felix** [comment]
Let me suggest: You use wayland?

**Comment by simonbcn** [comment]
Yes, why?

**Comment by haecker-felix** [comment]
Because it is a wayland bug. Happens on Firefox/gnome software too.

**Comment by simonbcn** [comment]
Firefox? I use Firefox and I haven't that problem. Do you know if this bug is reported to Gnome?

**Comment by haecker-felix** [comment]
Unfortunately no...

I should do a bug report...

**Comment by simonbcn** [comment]
Yes, if you want this problem to be solved. I suppose you, as a developer of this program, will have more information to help the Gnome developers to solve it. Is this problem related to MPRIS only? What's the problem with Firefox (I use Firefox and I don't detect this)? And with Gnome Software?

**Comment by simonbcn** [comment]
It works now with GNOME Shell 3.22.3 👍

**Comment by haecker-felix** [comment]
On 3.23 too 😄
