### ISSUE TITLE
Issues with high dpi screens

### ISSUE THREAD

**Issue by Ventajou** [haecker-felix/gradio#132]
I'm running Ubuntu with 1.5x scaling and some of the UI elements don't adapt properly. In particular, the buttons on the left in the Discover pane are cut in half. Here's an example below:

![image](https://cloud.githubusercontent.com/assets/732663/21715000/deb8f620-d3f9-11e6-80b1-ad7846d8f434.png)

**Comment by haecker-felix** [comment]
Gradio has a new layout now. It should be fixed with the new layout.
