### ISSUE TITLE
Add a metadata grabber

### ISSUE THREAD

**Issue by raphaelh** [haecker-felix/gradio#133]
Some radio stations don't include artist and track name in the stream, but these information can be found on their website, for example http://www.fipradio.fr/player

It would be nice to accept "extractors" like youtube-dl: https://github.com/rg3/youtube-dl/#adding-support-for-a-new-site

**Comment by haecker-felix** [comment]
Better solution:

https://github.com/haecker-felix/gradio/issues/134
