### ISSUE TITLE
Show menu button if it necessary

### ISSUE THREAD

**Issue by ET-Bent** [haecker-felix/gradio#136]
![gradio_001](https://cloud.githubusercontent.com/assets/5788982/21808663/89f81992-d744-11e6-8127-3e8aaef94f13.png)

![gradio_002](https://cloud.githubusercontent.com/assets/5788982/21808675/943754fe-d744-11e6-8c24-32e85459d340.png)

Either I am missing some button but for me, there is no way accessing the settings. Using Ubuntu Gnome 16.04.1. In Ubuntu 16.04.1 (Unity) I get the menu in the title bar as expected. On Gnome there should be some equivalent like a burger menu or 3-dot-menu.

**Comment by haecker-felix** [comment]
Click on "Gradio" in the top menu bar ;)

**Comment by ET-Bent** [comment]
First of all thanks for the help, see attached screenshot. I am using a shell extension called "Dash to Dock" which is really awesome. Adding a 3-dot-menu would really help. (Yes I know it's an issue with my special setup, but I assume some others may also be affected by this)

![image](https://cloud.githubusercontent.com/assets/5788982/21813427/7f05c32e-d756-11e6-9f4c-c26ed0190c14.png)

**Comment by julianrichen** [comment]
@ET-Bent If I recall their is an option in GNOME Tweak Tool under "Top bar" that lets you move the app menu from the top bar to the application window.

Might be a good temporary solution.

**Comment by haecker-felix** [comment]
Or apply the idea from @julianrichen. Gradio has a "three dot menu" in the header bar, but on the gnome shell it is hidden (because normally you have the app menu on the top)

The extension is awsome! How do get the clock/system tray into the bar?

**Comment by ET-Bent** [comment]
@haecker-felix see https://www.youtube.com/watch?v=MngJmIYRyL4

Repo: https://github.com/jderose9/dash-to-panel

Sadly this breaks app menu for Gradio ;)

**Comment by julianrichen** [comment]
@ET-Bent It might be because gradio is overriding the settings. From my understanding appmenu should be init in startup() of GtkApplication, like it is now in [src/core/gradio.vala:121](https://github.com/haecker-felix/gradio/blob/a23ba6e2e9acdc03e5c3f9ce576562c06873bbfd/src/core/gradio.vala#L121).

However it seems the appmenu is being re-created in [src/main-window.vala:73](https://github.com/haecker-felix/gradio/blob/a1917c98cb84e117d6952822ecbdab1d82388fc4/src/ui/main-window.vala#L73)

and then has this:
```vala
if(GLib.Environment.get_variable("DESKTOP_SESSION") == "gnome")
    MenuButton.set_visible (false);
else
    MenuButton.set_visible (true);
message("Desktop session is %s.", GLib.Environment.get_variable("DESKTOP_SESSION"));
```

@haecker-felix Or am I completely wrong, is GLib.MenuButton the same as menubar (and `gtk_application_set_menubar ()`)? I don't know the Vala bindings. It seems like the only thing that would disable the menu.

**Comment by ET-Bent** [comment]
How about a more manual implementation of this: As it works on stock Gnome 3 without any issue I'd not change this code. Rather would I suggest adding an option to the settings "force menu button in UI", so you can set it once you are in stock Gnome and then switch the Dash back to Dock.

**Comment by bil-elmoussaoui** [comment]
@haecker-felix I think you should use XDG_CURRENT_DESKTOP instead of DESKTOP_SESSION as it won't give the same result on wayland/xorg 
![screenshot from 2017-01-18 09-19-54](https://cloud.githubusercontent.com/assets/7660997/22056236/68322bd8-dd5f-11e6-9ecb-96d38fe16ca1.png)

**Comment by haecker-felix** [comment]
@bil-elmoussaoui XDG_CURRENT_DESKTOP on fedora: (null)
 
I could use the gtk fallback (moving the app menu in the headerbar), but this is not supported on unity. Unfortunately many people use gradio on unity. Annoying.

**Comment by dino99** [comment]
Currently i'm using gradio on Ubuntu 64 Zesty with a gnome-shell session, and a few apps from gnome-shell-extension as well.
I've not met the problem related here (maybe some conflicting versions ? mainly from non genuine archive).

I was first desapointed by the 'Empty Library' screen, before i finally understood what that was meaning, and finding it was possible to populate it with my favorite radio (hitting an also mysterious icon from the bottom bar). 
That said, it should be added some comments poped up when hovering these icons, to know what are they supposed doing, and replacing 'Library' by 'Favorite' for example (Library is too ambiguous and let us thinking about a missing system library needed by gradio)

**Comment by haecker-felix** [comment]
Gradio isn't overriding the fallback options anymore. The application menu is now visible.

@dino99 yes you're right, i'm working on it.
