### ISSUE TITLE
Invalid URI Issue

### ISSUE THREAD

**Issue by rstreeter** [haecker-felix/gradio#140]
No matter what station I try I get Invalid URI error.

**Comment by haecker-felix** [comment]
OS?
OS Version?
Gradio Version?

Maybe screenshot?

Sorry but I need more information.

**Comment by rstreeter** [comment]
Sorry, I forgot to add that stuff. 
I am running Xubuntu 16.04 
GRadio Version 5.0
![screenshot_2017-01-21_10-41-53](https://cloud.githubusercontent.com/assets/500779/22176011/8f7701dc-dfc6-11e6-9f19-13dbbb32dc22.png)

**Comment by andre-b** [comment]
Since today i get the same error. I use Gradio 5.0.12+r344-0~ubuntu16.04.1.

**Comment by rstreeter** [comment]
![screenshot at 10-47-14](https://cloud.githubusercontent.com/assets/500779/22176033/ffc58d64-dfc6-11e6-90cd-7e42df870143.png)
Here is the exact version I am using

**Comment by M0WYM** [comment]
Just powered up and get the same issue, was fine yesterday. Ubuntu 16.04 64-bit, Intel® Core™ i7-3770 CPU @ 3.40GHz × 8. 8GB RAM.

**Comment by haecker-felix** [comment]
Uhm I have the same problem since today. This is bad. Sounds like a server error. I will contact the administrator of the database. Thanks for the hint!

**Comment by haecker-felix** [comment]
Database returns now the old json structure again. Gradio is now working fine again (all versions). 

I don't know why the database returned a other json structure since today. But I will contact the developer for more information.

**Comment by haecker-felix** [comment]
I've contacted the dev of the database. It was a small error while repairing something else. All okay now!
