### ISSUE TITLE
Not possible to restore main window from tray icon

### ISSUE THREAD

**Issue by AlbertHilb** [haecker-felix/gradio#141]
If _Close to tray icon_ setting is selected, on closing GRadio window, its icon appears on the tray, but there is no way to reopen the app window.
I use KDE Plasma 5.8.5.

**Comment by haecker-felix** [comment]
Double click on the tray icon?

**Comment by AlbertHilb** [comment]
Does not work!

**Comment by cortopy** [comment]
experiencing same issue

**Comment by haecker-felix** [comment]
You have now 2 ways to restore gradio:
1) Click on the mpris panel 
2) Just start gradio from the startmenu, it restores the old session.

The tray icon option got removed because it is a deprecated technology.
