### ISSUE TITLE
List of Polish language radio stations is very small

### ISSUE THREAD

**Issue by FadeMind** [haecker-felix/gradio#143]
See: 

http://www.listenlive.eu/poland.html

https://github.com/FadeMind/archpkgbuilds/blob/77220091bf4f7aab315ddfde79c1f3967bc6b47b/AUR/customized/radiotray-hg/bookmarks.xml

**Comment by haecker-felix** [comment]
Feel free to add new stations

1. Discover - Sidebar - Add
2. radio-browser.info website.
