### ISSUE TITLE
Server does not support seeking

### ISSUE THREAD

**Issue by rcalvaga** [haecker-felix/gradio#144]
I'm getting interrupted radio streams. After a while, the stream stops, and instead of buffering and continuing, it shows an alert that "Server does not support seeking". It's necessary to play the station again.

**Comment by dino99** [comment]
i doubt the user can do something, as the problem is on the other side or between

**Comment by haecker-felix** [comment]
Not a problem of gradio itself. But there will be a auto reconnect feature soon.
