### ISSUE TITLE
Whole gradio application is slow

### ISSUE THREAD

**Issue by M0WYM** [haecker-felix/gradio#145]
gradio has been working fine until this morning when, at first, it took a minute or two to launch and then the UI was unresponsive - could not click on station. After a re-boot gradio refused to launch.

I' running Ubuntu 16.04 64 bit, Intel® Core™ i7-3770 CPU @ 3.40GHz × 8 , 8GB memory, graphics Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.8.0)

Any ideas before I try an uninstall-re-install?

Charlie.

**Comment by haecker-felix** [comment]
Launch gradio from a terminal and copy the output please. 
Thanks.

**Comment by M0WYM** [comment]
Hmm:
charlie@charlie-OptiPlex-980:~$ gradio
** Message: gradio.vala:173: >> Starting Gradio version 5.0.0 <<
** Message: gradio.vala:36: No existing window, starting new session.
** Message: settings.vala:24: Loaded settings module
** Message: library.vala:110: Reading library data from: /home/charlie/.local/share/gradio/library.gradio
** Message: station-registry.vala:35: [1] "WUMB Traditional Folk Stream - Boston, MA" is registered. (1 active stations)

About 60 sec wait after ** Message: library.vala:110

Then around same gap before five stations appear in terminal. No audio and no GUI.
Then:
** Message: library.vala:135: Successfully imported library data
** Message: main-window.vala:81: Desktop session is ubuntu.
** Message: category-item-provider.vala:36: Fetching category items...
** Message: utils.vala:96: Loaded CSS from: /usr/share/gradio/gradio.css

GUI then appears but unresponsive, time taken about 5 mins. Then about a minute later: 

** Message: audio-player.vala:155: Connecting to: http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p
** Message: station-registry.vala:58: [3] is now playing
and audio appears.


Charlie.

**Comment by M0WYM** [comment]
gradio seem to be very slowly registering stations, eg.

** Message: station-registry.vala:35: [66] "Echo of Moscow" is registered. (66 active stations)

Charlie.

**Comment by haecker-felix** [comment]
The output seems to be normal.

It is possible, that your internet connection is _very_ slow? 

Are other applications on your computer working normal?

**Comment by M0WYM** [comment]
Strange, download speed from server in London 87.77Mb/s, upload is 19.6Mb/s. Nothing much running, Thunderbird, Firefox and Vivaldi - mostly just open. DNS is google 8.8.8.8


Charlie.

**Comment by M0WYM** [comment]
OK, I still have the same issue. If I launch from a terminal then after some 5mins I get the last listened to station (BBC Radio4), then at some point later the GUI appears but does not function. If I try to launch the GUI instead of from a terminal nothing happens. I'm happy to supply any more info if needed. Charlie.

**Comment by SiRi13** [comment]
I had the same issue.
CLI output looked good, same as @M0WYM 
After I removed the library from `~/.local/share/gradio/`, gradio started as usual.
But now the 'Discover' tab takes at least three minutes to populate the columns.
After some more digging I found out that the problem is the DNS lookup, at least in my case. 
Adding a line in `/etc/hosts` solved it and gradio starts and responses right away. Even plays music :wink: 
I am just irritated by this because the problem occured from one day to the next..

**Comment by pimou** [comment]
hello,
I had the same issue but now all is working again without any modificition of my part.
Could you explain your modification in /etc/hots ?

**Comment by SiRi13** [comment]
Just added the IP address so no DNS lookup is necessary.
like so:
`37.120.178.42  radio-browser.info`
`37.120.178.42  www.radio-browser.info`

first line should be enough but didn't test it.
works as long _radio-browser.info_ points to IP _37.120.178.42_

**Comment by pimou** [comment]
thank you for your explanation

**Comment by haecker-felix** [comment]
Hello guys, can you check the latest git version please? There is a brand new library backend, and I'm sure the bug is fixed ;)

**Comment by haecker-felix** [comment]
No Feedback - I assume the issue is fixed. Please reopen the bug report if necessary.
