### ISSUE TITLE
Gradio is very slow

### ISSUE THREAD

**Issue by pimou** [haecker-felix/gradio#146]
Hello,
Same issue here.
After re-install, Gradio is very very slow, the GUI doesn't appear and doens't funtion :-(
Pimou.

**Comment by mickeythefixer** [comment]
Same problem here.
If I start it from a terminal, I can see that it's taking a *very* long time to register radio stations.

**Comment by dino99** [comment]
no problem on Ubuntu Zesty here, using a gnome-shell session (as gradio is a 'gnome' app)

**Comment by pimou** [comment]
now, gradio is working again... without any modifications of my part.

Problems with updates ? Same problem as  SiRi13 in #145?

**Comment by haecker-felix** [comment]
This is curios. I can _not_ cofirm this behavior.

Maybe it's a fault of your distribution. Which distribution are you using?

**Comment by haecker-felix** [comment]
Duplicate of #145. Closed.

**Comment by pimou** [comment]
I am using Arch Linux.
