### ISSUE TITLE
feature / copy song title

### ISSUE THREAD

**Issue by patdum** [haecker-felix/gradio#147]
Hi,

This is a feature request.

At the botton of software appears a panel with informations about track currently playing on the radio.

May it be possible to copy these informations?
Actually, we can not select song name and do a CTRL+C.

It is useful when a song enjoys you and want to write down it.

Thank for your software, very nice.

**Comment by dino99** [comment]
i suppose you already have heard something called 'piracy'

**Comment by haecker-felix** [comment]
Why this should be piracy 😄 ? You just copy the title of the song.

@patdum : Yes this is no problem. Next version!

**Comment by patdum** [comment]
My need is to copy a song title to buy the CD, perhaps others may copy to bittorent.. I don't know that copy the title of a song should be piracy...
