### ISSUE TITLE
When the station uses icy-title for now playing gradio spams a notifcation

### ISSUE THREAD

**Issue by ioangogo** [haecker-felix/gradio#148]
Reproduction step: Play radio X, get spam

what should happen The notification only shows when the icy-title changes

what happens: i get spam all the way through a song

The spammyness seems to match the speed of the stuff in MPD's logs when I listen to the same station through that, so it is to do with the frequency the station sends new titles through to how noticible it is 

if you need more info, just ask

**Comment by ioangogo** [comment]
Here is the video of the issue https://www.youtube.com/watch?v=XVw-p_e3q-Y&feature=youtu.be as you can see the notification bobbing and constantly updating

**Comment by ioangogo** [comment]
Turns out that the radio station is at fault according to the shoutcast spec, but it is unlikely to be possible get them to change what they are doing. I have discovered this due to trying to report the same issue to the MPD dev

**Comment by haecker-felix** [comment]
Hm, cannot reproduce this bug anymore with the latest dev version of gradio. Please test it with gradio 6 (going to be released soon!), and reopen this bug report, if the issue is still persist. Thanks
