### ISSUE TITLE
Add Solus to the readme

### ISSUE THREAD

**Issue by Vistaus** [haecker-felix/gradio#150]
You might want to add Solus to the readme as well 'cause it has GRadio in the default repositories, as you can see here: https://git.solus-project.com/packages/gradio/

Installing is just a matter of opening up the Software Center and searching for and installing GRadio. Or sudo eopkg it gradio

:smile_cat:

**Comment by haecker-felix** [comment]
thanks for the hint!

**Comment by Vistaus** [comment]
You're welcome and thanks for adding it so quickly! :smile:
