### ISSUE TITLE
weird window

### ISSUE THREAD

**Issue by arnauldb** [haecker-felix/gradio#151]
I installed gradio on ubuntu via ppa, I launch it then have this window and nothing else...

![selection_006](https://cloud.githubusercontent.com/assets/13196747/22983360/29d862c2-f3a2-11e6-9d9a-5146c03c2864.png)

thanks for help.

**Comment by haecker-felix** [comment]
Seems to be normal. You have add new stations to your library. Just click on discover.

**Comment by arnauldb** [comment]
ok, I didn't get it and didn't click on "discover"... I added a few radios and it is working fine. Thank you for gradio !
