### ISSUE TITLE
Does not appear in the tray even after restarting gradio

### ISSUE THREAD

**Issue by RomanKoshelev** [haecker-felix/gradio#155]
![image](https://cloud.githubusercontent.com/assets/9590406/23496097/580df166-ff2d-11e6-94f7-235af14d24a3.png)

**Comment by RomanKoshelev** [comment]
Yet after restarting

**Comment by haecker-felix** [comment]
I've removed the tray icon option, because it is a deprecated technology. Just use the mpris panel, it have the same features.
