### ISSUE TITLE
Show *which* codec is missing.

### ISSUE THREAD

**Issue by fturco** [haecker-felix/gradio#157]
I use gradio (latest git version) on Gentoo Linux. When playing the m2o radio I get the following warning message:

> A codec is missing!

It doesn't say which codec it is talking about. Perhaps I need to install some gstreamer package.

If I try running `gradio` from the command line I get the following warning message, multiple times:

> ** Message: audio-player.vala:60: Check if codec is missing...

This is the list of gstreamer plugins on my system:

```
$ eix --installed --only-names gst-plugins
media-libs/gst-plugins-bad
media-libs/gst-plugins-base
media-libs/gst-plugins-good
media-libs/gst-plugins-ugly
media-plugins/gst-plugins-a52dec
media-plugins/gst-plugins-cdparanoia
media-plugins/gst-plugins-dts
media-plugins/gst-plugins-dvdread
media-plugins/gst-plugins-faad
media-plugins/gst-plugins-flac
media-plugins/gst-plugins-gdkpixbuf
media-plugins/gst-plugins-hls
media-plugins/gst-plugins-jpeg
media-plugins/gst-plugins-libav
media-plugins/gst-plugins-libmms
media-plugins/gst-plugins-libnice
media-plugins/gst-plugins-mad
media-plugins/gst-plugins-meta
media-plugins/gst-plugins-mpeg2dec
media-plugins/gst-plugins-opus
media-plugins/gst-plugins-pulse
media-plugins/gst-plugins-resindvd
media-plugins/gst-plugins-soup
media-plugins/gst-plugins-taglib
media-plugins/gst-plugins-v4l2
media-plugins/gst-plugins-vpx
media-plugins/gst-plugins-x264
```

**Comment by cunei** [comment]
Same here. I'm trying to play [this HLS stream](http://b2.httpstream2.rai.it/venezia1_audioH24.isml/QualityLevels(128000)/manifest(format=m3u8-aapl).m3u8) and I get the same message. It would be nice to be able to determine which (if any) particular codec is missing.

**Comment by haecker-felix** [comment]
In the next version of gradio you can check which codec is required for a station.

Right click a station -> Details

![grafik](https://user-images.githubusercontent.com/6001248/34467179-0bd54abc-eeea-11e7-9ffb-459dc57b8d24.png)
