### ISSUE TITLE
Improve the "More stations" behavior

### ISSUE THREAD

**Issue by Zorrodacat** [haecker-felix/gradio#159]
Not really a bug. Just a request. 

In case you wanna make it easier to browse all channels...Sometimes even narrowing to your state/province still needs you to press 'More....' forever... Would like a 'Show all' button or something....Would like to download all the stations for a given search criteria

see the green arrow below if you don't understand what I'm talking about...Thanks.... Very nice work....light, fast and many stations..Much better than TuneIn on Winblows (which contains ads)

With little adjustments, it looks like a KDE app on KDE5 Plasma... :-) Really happy with this app. No need to illegally download music with all these channels...this is cool and legit. 
 
Have a great day :) Peace. 
<img width="960" alt="more" src="https://cloud.githubusercontent.com/assets/26261843/23680918/edfa080a-035a-11e7-8e28-f2db53a1e836.png">

**Comment by haecker-felix** [comment]
"Load all"  would be a overkill. Sometimes there are thousands of stations to show. It would eat your RAM.

It is possible that automatic more stations get loaded if you scroll at the end of the current page, but this feature would require GTK 3.18 or newer.

Maybe I can bumb the gtk Version to 3.20 with the next release of gradio. Then it would be possible to add something like this.

**Comment by paulcarroty** [comment]
@haecker-felix I agree this issue. If you find the station with "More.." it hurts. Maybe the classical options 'Show 100' or 'Show 200 stations' will increase the UX.

**Comment by haecker-felix** [comment]
The actual maximum of search results is now limited to 100 items. However you can edit the value in a dconf editor. 

The search results are now extremely filterable, and so you don't need much more items.
