### ISSUE TITLE
Improve the audio backend

### ISSUE THREAD

**Issue by konkor** [haecker-felix/gradio#161]
I have installed the app from github/master source. And I have few issues:
1. Player stop playing about after 1 minute (i think here some unhadled exception).
I have this massage after start playing.
```
** Message: station-registry.vala:58: [2] is now playing
```
and after stopping playing i have only 1 message:
```
** Message: audio-player.vala:72: Server does not support seeking.
```
2. No icon (just default gtk failure icon) in system tray (notification area).
3. No icon for "Likes" (the same here just default gtk icon).

**Comment by konkor** [comment]
with GST_DEBUG="*:2" i have this:
```
0:01:22.650858127  7228 0x7f06c8005a40 WARN                   pulse pulsesink.c:702:gst_pulsering_stream_underflow_cb:<pulsesink1> Got underflow
0:01:33.788230703  7228      0x17b4320 WARN             souphttpsrc gstsouphttpsrc.c:1218:gst_soup_http_src_got_headers_cb:<source> error: Server does not support seeking.
0:01:33.788285912  7228      0x17b4320 WARN             souphttpsrc gstsouphttpsrc.c:1218:gst_soup_http_src_got_headers_cb:<source> error: Server does not accept Range HTTP header, URL: http://icecastdc.luxnet.ua/lux, Redirect to: (NULL)
** Message: audio-player.vala:72: Server does not support seeking.
0:01:33.788384452  7228      0x17b4320 WARN                 basesrc gstbasesrc.c:2933:gst_base_src_loop:<source> error: Internal data flow error.
0:01:33.788432072  7228      0x17b4320 WARN                 basesrc gstbasesrc.c:2933:gst_base_src_loop:<source> error: streaming task paused, reason error (-5)
** Message: audio-player.vala:72: Internal data flow error.
0:01:33.788553810  7228 0x7f07a8001c00 WARN            audiodecoder gstaudiodecoder.c:1460:gst_audio_decoder_drain:<faad0> still 1 frames left after draining
```

**Comment by konkor** [comment]
so have this error on switching of stations
```
0:07:15.949660192  7228      0x1661520 ERROR                GST_BUS gstbus.c:857:gst_bus_add_watch_full_unlocked:<bus1> Tried to add new watch while one was already there
```
I think You have to move the part to constructor:
```
Gst.Bus bus = stream.get_bus ();
bus.add_watch (1, bus_callback);
```

**Comment by konkor** [comment]
So the player stops not on all stations... I think u have to build more complex pipeline to handle this streams.
PS: u can take a look at C GStreamer backend for banshee https://github.com/GNOME/banshee/tree/master/src/Backends/Banshee.GStreamer/libbanshee He works very well with any audio/video stream.

**Comment by haecker-felix** [comment]
Yeah I have to admit the current gstreamer implementation is very basic. I've creates it in Gradio 1.x and never changed it since then. It needs many improvements in 6.x.

**Comment by haecker-felix** [comment]
Gradio 6 is going to have a new audio backend. The code is already  on master!
