### ISSUE TITLE
m3u8 streams playing but "a codec is missing" error appears

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#164]
Hi,

Gradio can play m3u8 streams, but an annoying "a codec is missing" error appears every two seconds. A "connection information" message follows it with info about codec as MPEG-4 AAC, no channel info and, I think, relatively small bitrate values. While the error messages active, the window waits to dismiss it by clicking somewhere before you use menues, etc

For example this station:
http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8
(homepage: http://radyo.trt.net.tr/Kanal/3/radyo-3.aspx )

By the way, thanks for this excellent software!

**Comment by sispus** [comment]
In addition, bitrate vaues are unstable, changing from 30s to 90s (I'm not sure if its meaningfull or not; but for other stations it doesn't change that much).

**Comment by haecker-felix** [comment]
Fixed with the latest commits. I've implemented a new audio backend, which should fix these messages.
