### ISSUE TITLE
tray icon is inactive

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#165]
Hi, well, again.

I'm using plasma desktop on ubuntu 16.04. Tray icon is totally useless here, no left click, no right click, etc. Desktop's "media player" widget shows info about station and music. I can right click on this widget's tray icon to "open" and "quit" Gradio, but its play-pause button doesn't work. Media key (play-pause) works.

I don't know if te station can be changed or radio paused from tray icon. If no, moedia player wdget tray icon gets its function. But It would be good to change station, pause-play, and even change sound by mouse wheel from tray icon.

And again, thanks :)

**Comment by haecker-felix** [comment]
I've removed the tray icon option, because it is a deprecated technology. Just use the mpris panel ;)

**Comment by Mikaela** [comment]
Has there not been a new version since this? I just installed the app from Flathub and experienced this problem.
