### ISSUE TITLE
Error on Gradio 5.0.0 on Ubuntu Mate 16.04.2

### ISSUE THREAD

**Issue by CocoCocoAlx** [haecker-felix/gradio#166]
I am trying to reproduce the following radio: <http://disneyargradio-lh.akamaihd.net/i/ARG_Disney_RADIO@102438/master.m3u8> and Gradio asks me to install the gstreamer1.0-plugins-bad library, which is already installed on my system. I tried with 32 and 64 bits versions of this libraries... With other applications, like VLC, it is possible to reproduce the stream.

Attached technical information for better support. Regards!

System:
Kernel: 4.8.0-46-generic x86_64 (64 bit)
Desktop: MATE 1.16.1  Distro: Ubuntu 16.04 xenial
Machine: Mobo: ASUSTeK model: P5KPL-AM SE v: X.0x
Bios: American Megatrends v: 0702 date: 08/20/2010
CPU: Quad core Intel Core2 Quad Q9400 (-MCP-) speed/max: 1998/2664 MHz
Graphics:
Card: Advanced Micro Devices [AMD/ATI] RV730 PRO [Radeon HD 4650]
Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
Libraries:
dpkg --get-selections | grep gstreamer

gir1.2-gstreamer-1.0                            install
gstreamer1.0-alsa:amd64                         install
gstreamer1.0-clutter-3.0                        install
gstreamer1.0-libav:amd64                        install
gstreamer1.0-libav:i386                         install
gstreamer1.0-nice:amd64                         install
gstreamer1.0-plugins-bad:i386                   install
gstreamer1.0-plugins-bad-faad:amd64             install
gstreamer1.0-plugins-bad-faad:i386              install
gstreamer1.0-plugins-bad-videoparsers:amd64     install
gstreamer1.0-plugins-bad-videoparsers:i386      install
gstreamer1.0-plugins-base:amd64                 install
gstreamer1.0-plugins-base:i386                  install
gstreamer1.0-plugins-good:amd64                 install
gstreamer1.0-plugins-good:i386                  install
gstreamer1.0-pulseaudio:amd64                   install
gstreamer1.0-tools                              install
gstreamer1.0-x:amd64                            install
gstreamer1.0-x:i386                             install
libgstreamer-plugins-bad1.0-0:amd64             install
libgstreamer-plugins-bad1.0-0:i386              install
libgstreamer-plugins-base1.0-0:amd64            install
libgstreamer-plugins-base1.0-0:i386             install
libgstreamer-plugins-good1.0-0:amd64            install
libgstreamer-plugins-good1.0-0:i386             install
libgstreamer1.0-0:amd64                         install
libgstreamer1.0-0:i386                          install
libreoffice-avmedia-backend-gstreamer           install
phonon-backend-gstreamer:amd64                  install
phonon-backend-gstreamer-common:amd64           install

**Comment by oxoocoffee** [comment]
Yup I did see this too. Current work around is to make sure there is no other GRadio process running in background. I get this every time I close GRadio and reopen but the old process is hanging around. After killing all back to normal for me.

**Comment by haecker-felix** [comment]
The next version of gradio has a new audio backend. It's very likely that this bug will be fixed in the next version, which will be released soon.

If you have still problems with gradio 6, please reopen this bug report.
