### ISSUE TITLE
Ubuntu artful complain about an unfound mpeg-1 layer

### ISSUE THREAD

**Issue by dino99** [haecker-felix/gradio#168]
On a Artful real install with a gnome-shell session:
- using the 'artful' version of the ppa: when wanting to listen a library, get some missing codecs warning, like gstreamer1.0-plugins-ugly, which can be installed with other dependencies. But again, on the next icon click, a warning about an unfound MPEG-1 Layer is displayed. I have tried many additional dependencies supposing to work with the MPEG1/2/3, but no avail.

- purging the Artful version, changing the ppa source to 'zesty', uploading and reinstalling gradio, it then works as expected.

**Comment by haecker-felix** [comment]
If you install a new codec, you need to restart gradio itself, to apply the new installed codec. 

You purged gradio from your system, and installed a another version, that was the "restart", which was needed ;)
