### ISSUE TITLE
crash on ubuntu 16.04

### ISSUE THREAD

**Issue by segler-alex** [haecker-felix/gradio#17]
i use version 3.0.1

segler@gaia:~$ gradio 
** Message: Gradio.vala:133: Starting Gradio version 3.0.1!
** Message: MPRIS.vala:21: Successfully initialized MPRIS session.
** Message: Library.vala:90: Reading library data from: /mnt/data/segler/.local/share/gradio/library.gradio
** Message: Library.vala:109: No gradio library found. 
** Message: Library.vala:115: Successfully imported library

(gradio:32183): Gtk-CRITICAL **: Error building template class 'GradioDiscoverBox' for an instance of type 'GradioDiscoverBox': .:5:1 Required gtk+ version 3.20, current version is 3.18

(gradio:32183): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(gradio:32183): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(gradio:32183): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(gradio:32183): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(gradio:32183): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gradio:32183): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gradio:32183): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(gradio:32183): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by haecker-felix** [comment]
This bug should be fixed in Gradio 3.0.2. Updated package for ubuntu soon.

**Comment by haecker-felix** [comment]
https://github.com/haecker-felix/gradio/releases/tag/v3.0.2

**Comment by torpet** [comment]
Same bug in version 4.0.

**Comment by haecker-felix** [comment]
@torpet could you copy the output? I need the exactly information.

**Comment by torpet** [comment]
https://gist.github.com/torpet/71ce34e03c499088eb1cad5fc0a73953

what's funny though is that on another system with Ubuntu 16.04.1, gradio works completely fine. Could this a missing dependency masked as a version mismatch?

**Comment by haecker-felix** [comment]
@torpet your output is from the 3.0 version. You need to upgrade your gradio version.
