### ISSUE TITLE
Can't seem to right click on the 'most popular' column on the discover tab

### ISSUE THREAD

**Issue by i30817** [haecker-felix/gradio#171]
I have major connection speed problems first so i couldn't in any of them, until i put in the /etc/hosts ip for your app, but my connection is still terrible.

Anyway, besides that, now only the most popular radios aren't reacting to right click. I also noticed that this is the only column without a viewport scrollbar, which seems strange, even if it is a dynamic viewport. Maybe related?

edit: this also happens even with a normal search. In spite of the 'normal' search looking like it replaces the '3 columns' by a single list going left to right, top bottom with a single viewport, the mouse scroll and right click still only reacts on the center and right 'columns' and icons respectively. Another strange clue.

**Comment by haecker-felix** [comment]
Fixed.

**Comment by i30817** [comment]
Sorry to bother you @haecker-felix , but this happened again on the 'global search' results. The leftmost column can't be clicked.

**Comment by haecker-felix** [comment]
@i30817 which version of gradio?

**Comment by i30817** [comment]
> dpkg-query -s gradio
> Package: gradio
> Status: install ok installed
> Priority: extra
> Section: x11
> Installed-Size: 494
> Maintainer: Felix Häcker <haecker.felix1207@gmail.com>
> Architecture: amd64
> Version: 5.0.12+r344-0~ubuntu16.04.1
> Depends: dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.39.4), libgstreamer-plugins-base1.0-0 (>= 1.0.0), libgstreamer1.0-0 (>= 1.0.0), libgtk-3-0 (>= 3.18), libjson-glib-1.0-0 (>= 0.12.0), libsoup2.4-1 (>= 2.41.90)
> Description: Internet Radio
>

**Comment by haecker-felix** [comment]
This bug is already fixed in master. The fix will be included in the next stable release of gradio (6.0)

**Comment by i30817** [comment]
Ah, i thought the ppa was autobuild.
