### ISSUE TITLE
Segmentation error (the memory stack is flushed to disk)

### ISSUE THREAD

**Issue by ForumLiker** [haecker-felix/gradio#172]
$ gradio
** Message: gradio.vala:173: >> Starting Gradio version 5.0.0 <<
** Message: gradio.vala:36: No existing window, starting new session.
** Message: settings.vala:24: Loaded settings module

(gradio:6711): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: library.vala:110: Reading library data from: /home/pmpo/.local/share/gradio/library.gradio
** Message: library.vala:129: No Gradio library found.
** Message: library.vala:135: Successfully imported library data
** Message: main-window.vala:81: Desktop session is (null).

(gradio:6711): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: category-item-provider.vala:36: Fetching category items...
** Message: utils.vala:96: Loaded CSS from: /usr/local/share/gradio/gradio.css
** Message: gradio.vala:74: Continue playback
** Message: station-registry.vala:35: [1] "MFM STATION" is registered. (1 active stations)
Segmentation error (the memory stack is flushed to disk)

The reinstallation of the package did not help

**Comment by haecker-felix** [comment]
The next version of gradio has a new library backend. Please try the latest version (master).

**Comment by ForumLiker** [comment]
gradio
** Message: gradio.vala:173: >> Starting Gradio version 5.0.0 <<

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2521:75: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2880:24: '0' is not a valid color name

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3708:68: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3724:74: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3740:74: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3756:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3772:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3788:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3803:64: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3818:70: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3833:70: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3848:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3863:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3878:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4726:73: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4738:87: Using one color stop with linear-gradient() is deprecated.
** Message: gradio.vala:36: No existing window, starting new session.
** Message: settings.vala:24: Loaded settings module

(gradio:3493): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: library.vala:110: Reading library data from: /home/pmpo/.local/share/gradio/library.gradio
** Message: library.vala:129: No Gradio library found.
** Message: library.vala:135: Successfully imported library data

(gradio:3493): Gtk-CRITICAL **: Unable to retrieve object 'VolumeButton' from class template for type 'GradioMainWindow' while building a 'GradioMainWindow'

(gradio:3493): Gtk-CRITICAL **: gtk_menu_button_set_menu_model: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed

(gradio:3493): Gtk-CRITICAL **: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed
** Message: main-window.vala:81: Desktop session is (null).

(gradio:3493): Gtk-CRITICAL **: gtk_button_set_relief: assertion 'GTK_IS_BUTTON (button)' failed

(gradio:3493): Gtk-CRITICAL **: gtk_scale_button_set_value: assertion 'GTK_IS_SCALE_BUTTON (button)' failed

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2521:75: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2880:24: '0' is not a valid color name

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3708:68: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3724:74: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3740:74: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3756:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3772:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3788:80: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3803:64: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3818:70: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3833:70: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3848:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3863:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3878:76: Expected ')' at end of '-gtk-scaled'

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4726:73: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4738:87: Using one color stop with linear-gradient() is deprecated.

(gradio:3493): Gtk-CRITICAL **: Unable to retrieve object 'LikesLabel' from class template for type 'GradioPlayerToolbar' while building a 'GradioPlayerToolbar'

(gradio:3493): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed

(gradio:3493): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed

(gradio:3493): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed

(gradio:3493): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed
Segmentation error (the memory stack is flushed to disk)
