### ISSUE TITLE
PPA not signed and no Pubkey found.

### ISSUE THREAD

**Issue by OldDog42** [haecker-felix/gradio#173]
Using Gradio Ver 5.0.  
OS Linux Mint 18.2 (Beta) Cinnamon 64bit
Cinnamon Ver 3.4.1
Kernel 4.8.0-53-generic

Radio plays and works as advertised!
However, I am receiving errors:
W: GPG error: http://ppa.launchpad.net/haecker-felix/gradio-daily/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B89978029F7DC26C
W: The repository 'http://ppa.launchpad.net/haecker-felix/gradio-daily/ubuntu xenial InRelease' is not signed.

I enjoy the app and Thanks for all you do.

**Comment by haecker-felix** [comment]
The PPA no longer exists and is no longer supported. I only maintain the flatpak and snap version from now on.

More Information:
https://github.com/haecker-felix/gradio/wiki/Install-Gradio
