### ISSUE TITLE
git maste fails to build

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#174]
Trying to build latest git master ends with following error message
`Python detected LC_CTYPE=C: LC_CTYPE & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).`

**Comment by haecker-felix** [comment]
I think you fixed it yourself :-)

**Comment by HeikoAdams** [comment]
No, unfortunedly not. Following the instructions in the wiki lead to this:
`+ meson . --prefix /usr
Python detected LC_CTYPE=C: LC_CTYPE & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).`

**Comment by HeikoAdams** [comment]
Okay, latest git master builds but fails with
`ninja: error: loading 'build.ninja': No such file or directory`

**Comment by haecker-felix** [comment]
After you have run meson, you have to enter the new build dir.

meson . build              // Generates the build files
cd build                       // go into the new build folder
ninja                            // build the project itself
