### ISSUE TITLE
Bring back tray icon (at least for non Gnome desktops)

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#176]
Commit d355aa42c02228ba9d5f99f1a41a26fa37908ed6 removed the tray icon because it is a deprecated technology. But Desktops like Xfce still use this technology so it would be nice if gradio would do so too on these desktops.

**Comment by haecker-felix** [comment]
The problem is, it is deprecated since gtk 3.14, which means it gets removed soon. I want to keep my code free of deprecated things, because then it is easier to port it to newer libs, for example, to gtk4. 

I know tray icons are useful for few desktop shells, i'm thinking for a solution. Maybe I can implement a plugin system, where 3rd party plugins can be loaded.

On modern desktops (for example gnome3), tray icons got be replaced by notifications and mpris.

**Comment by ruXlab** [comment]
As ubuntu/unity user I still prefer to have a try icon.
Is it possible to optionally enable this _depricated_ feature if it's available? It'd be very convenient 

Thanks

**Comment by pongraczi** [comment]
Hi, +1, I use MATE and personally I am not a big fan of the unity and other "modern" desktops.
Maybe it will change in the future, but at this moment for me tray icon is missing, I got only a blank area on the tray.

**Comment by haecker-felix** [comment]
The tray icon is going to have a comeback. But only for as long as it's possible (tray icon is already a deprecated technology, it is going to be removed in gtk4.)

**Comment by haecker-felix** [comment]
"fixed" with  2eb2e48

**Comment by pongraczi** [comment]
Felix, thank you!

Background information, no need an action:  
_I researched the reason, why try icons are deprecated and I found that, it is mostly true for Unity/Gnome3, where developers just dropped that feature for several reasons (technology and conceptual).
From my point of view, unity and gnome3 are the worst desktop managers ever and I do not want to use them. Seems Mate is the way I should still use in the future, while others use xfce, lxe, where tray also has meanings.
I use the try icons as indicators: vpn connection, dropbox, nextcloud, volume control, screenshot, etc. Even I miss a notification (lost vpn connection, non-working or just syncing dropbox/nextcloud etc.) I can see the situation in one sight without any interaction (switch to the application and see there.
It seems lot of people think, dropping tray icons is stupid, others think it is not a big deal and could be annoying - especially in windows.
So, in really short this is the reason, why Felix wrote, it is a deprecated technology, even there are other DEs than unity/gnome3._
