### ISSUE TITLE
Transparent background makes impossible to read menu

### ISSUE THREAD

**Issue by ruXlab** [haecker-felix/gradio#178]
Hello and thank you for the project!

I have this UI issue 
![screenshot from 2017-06-23 11-17-41](https://user-images.githubusercontent.com/1110234/27477920-a2933724-5805-11e7-820d-4c428c953192.png)

Right drawer menu has transparent background for all items: languages, countries, tags and states

gradio: 5.0.12+r344-0~ubuntu17.04.1
ubuntu 17.04

**Comment by haecker-felix** [comment]
duplicat of #125. Already fixed in master.
