### ISSUE TITLE
Development Version.

### ISSUE THREAD

**Issue by albfneto** [haecker-felix/gradio#181]
Dear Si, i followed your guide for install the development version in Sabayon (Gentoo based Distro),
https://github.com/haecker-felix/gradio/wiki/Install-Gradio
prior, i installed the packages: meson, ninja and vala.
command meson build . worked, 

go to build dir , OK
command ninja: 
then, in the build dir, command ninja not works.... message:

ninja: error: loading 'build.ninja': No such file or directory
the only files in the dir build, are:

 ls -a
.  ..  meson-logs  meson-private

**Comment by haecker-felix** [comment]
Make sure you are in the root directory of gradio. (data/src/...)

Here you run 

meson build .

This creates a new dir named "build". Enter it with "cd build". 
Now just run "ninja".

This should work. If not, I have to test it on sabayon myself.

**Comment by haecker-felix** [comment]
Just reopen it, if the issue still persists.
