### ISSUE TITLE
help for compilation

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#183]
I get that error message while compiling 5.9 in opensuse 42.2:

>  Meson encountered an error in file data/meson.build, line 6, column 0:
>  Unknown function "join_paths".

I followed that:
- git clone https://github.com/haecker-felix/gradio.git
- cd gradio
- meson build .

First, it said there is no 'build' folder, so I create a folder named 'build' inside gradio folder. 
Then, I install all missing dependencies which are stopped the building (listed in /gradio/meson.build).
Then I get this message.

_terminal was like that:_
 

> The Meson build system
> Version: 0.33.0
> Source dir: /home/luna/gradio
> Build dir: /home/luna/gradio/build
> Build type: native build
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Project name: gradio
> Native vala compiler: valac (unknown 0.32.1)
> Native c compiler: cc (gcc 4.8.5)
> Library m found: YES
> Found pkg-config: /usr/bin/pkg-config (0.28)
> Native dependency glib-2.0 found: YES 2.48.2
> Native dependency gobject-2.0 found: YES 2.48.2
> Native dependency gio-2.0 found: YES 2.48.2
> Native dependency gtk+-3.0 found: YES 3.20.10
> Native dependency libsoup-2.4 found: YES 2.54.1
> Native dependency json-glib-1.0 found: YES 1.2.2
> Native dependency gstreamer-1.0 found: YES 1.12.1
> Native dependency gstreamer-pbutils-1.0 found: YES 1.12.1
> Native dependency sqlite3 found: YES 3.8.10.2
> Warning, glib compiled dependencies will not work reliably until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
> Program msgfmt found: YES (/usr/bin/msgfmt)
> 
> Meson encountered an error in file data/meson.build, line 6, column 0:
> Unknown function "join_paths".
> 

Where were I wrong?
Thanks

**Comment by haecker-felix** [comment]
You need meson 0.36.0 or higher.
