### ISSUE TITLE
Details Panel doesn't update when you change stations

### ISSUE THREAD

**Issue by alex285** [haecker-felix/gradio#186]
Reproduce:

1. on Library View pick a station and right click to bring selection mode
2. click on "Details" button
3. then change station

Output:
Details Panel will remain on old station

Expected:
Details Panel should update to the newly selected station

Additionally:
perhaps Details panel should be toggle-able without need to enter on selection mode

**Comment by haecker-felix** [comment]
I cannot reproduce it. Could you provide more details?

Note: To update the details sidebar, you have to right click a station, and click "Details".

**Comment by dasnoopy** [comment]
.. maybe, just as little usability improvement,  when you change and play another  radio station, the  details panel should be automatically updated without click  the details button again..

**Comment by alex285** [comment]
@haecker-felix  the same that @dasnoopy  says

**Comment by haecker-felix** [comment]
So it isn't a bug, it is a feature request ;)
