### ISSUE TITLE
[Fedora 25+] Fix for missing codecs (consider adding to wiki)

### ISSUE THREAD

**Issue by rjleaf** [haecker-felix/gradio#187]
Information should be included in the Wiki about resolving missing codec issues with Gradio. I was able to fix issues with MP3 playback by following the instructions [over here](http://www.binarytides.com/multimedia-codecs-fedora-23/). 

## Solution

1. Install RPMFusion
    ```
    su -c 'dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
    ```

2. Install relevant plugins (some are non-free)
     ```
     sudo dnf install gstreamer1-plugins-base gstreamer1-plugins-good gstreamer1-plugins-ugly gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free gstreamer1-plugins-bad-freeworld gstreamer1-plugins-bad-free-extras ffmpeg
     ```

3. (Optional) Restart gradio and enjoy.

**Comment by haecker-felix** [comment]
The next version of gradio is going to be packed as a flatpak, so it should'nt be a problem.
