### ISSUE TITLE
No settings on Xfce

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#188]
When running gradio _(latest git master)_ on Xfce there is no way to access application settings:
![bildschirmfoto_2017-07-11_19-51-14](https://user-images.githubusercontent.com/1418818/28082346-83fba50a-6672-11e7-9cb7-e133b9ddc88f.png)

**Comment by haecker-felix** [comment]
Was there a menubar before?

**Comment by HeikoAdams** [comment]
AFAIR yes
