### ISSUE TITLE
Excessive memory use? (or expected fixed buffer size?)

### ISSUE THREAD

**Issue by wefunkster** [haecker-felix/gradio#193]
![bildschirmfoto von 2017-07-24 07 36 07](https://user-images.githubusercontent.com/20444615/28509512-2b9714b4-7043-11e7-9a60-28777c88c691.png)

Is this a normal amount of RAM for Gradio? (used for buffer?)

Also when I stop and close it, it stays in the background and doesn't free the memory. 
Is this because you can continue to play in the background with the app closed? (even when stopped before)

Wouldn't just minimizing the app do the same job to play in the background?
... and quit it completely on close?

Otherwise an absolutely essential app for me and my wife! 
No issues. Runs stable and does the job. Sorting favourite stations would be the icing on the cake!

**Comment by haecker-felix** [comment]
In version 5.x there was a huge memory leak, which is already fixed.

In the next release you can also sort your library to whatever you want.

Currently I'm doing code optimization, then I'm going to release 6.0.

**Comment by wefunkster** [comment]
This is great! 
Thanks for your very quick reply ... and your outstanding work on this nifty app!
Highly appreciated!
