### ISSUE TITLE
Segmentation Fault when you use GNOME media player indicator and ctrl+play without a station selected

### ISSUE THREAD

**Issue by i30817** [haecker-felix/gradio#194]
To reproduce install both gradio and https://extensions.gnome.org/extension/55/media-player-indicator/
enable the plugin, start gradio with some radio stations already added (but without starting one) and press ctrl+play.

I'm 'pretty sure' that what is crashing is gradio because well, it's what crashes with a segmentation fault

**Comment by haecker-felix** [comment]
Which version of gradio?

**Comment by i30817** [comment]
5.0.0

**Comment by haecker-felix** [comment]
Fixed, fix will be included in the next version of gradio
