### ISSUE TITLE
feature request: keyboard shortcuts to play / pause radio, switch to next station

### ISSUE THREAD

**Issue by arooni** [haecker-felix/gradio#198]
would love to see this; right now i have to switch to a virtual desktop and play/pause from there.  a tray icon i could access might be another approach but having universal keyboard shortcuts accessible outside the app would be convenient.

**Comment by haecker-felix** [comment]
Keyboard shortcuts outside the app are not possible  (see wayland security). But gradio use MPRIS, so if you have special media buttons on your keyboard you can use them.

On some desktop environments there is also a extra MPRIS applet available in the sound menu.

A tray icon is available too.

**Comment by haecker-felix** [comment]
In the app itself you can use ctrl and space to toggle the playback
