### ISSUE TITLE
PPA problem

### ISSUE THREAD

**Issue by HarryComber** [haecker-felix/gradio#200]
Installing to Linux Mint when I add the repository (sudo add-apt-repository ppa:haecker-felix/gradio-daily)  and then run sudo apt-get update,  I get the message: 
W: Failed to fetch http://ppa.launchpad.net/haecker-felix/gradio-daily/ubuntu/dists/trusty/main/source/Sources  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/haecker-felix/gradio-daily/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found 
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by haecker-felix** [comment]
The PPA no longer exists and is no longer supported. I only maintain the flatpak and snap version from now on.

More Information:
https://github.com/haecker-felix/gradio/wiki/Install-Gradio
