### ISSUE TITLE
How can I add a custom station?

### ISSUE THREAD

**Issue by sphh** [haecker-felix/gradio#201]
How can I add a custom station to my library if it cannot discovered in Gradio 5.0.0?

#12 says that it is implemented in 5.x, but I cannot find the appropriate button/menu (item)...

**Comment by konkor** [comment]
You have to add it on the website first. Google it

**Comment by haecker-felix** [comment]
In the discover page, there is a "+" button in the sidebar. Just click it ;)

**Comment by sphh** [comment]
Thanks.

A couple of thoughts:

- When I started gradio, the window was not high enough to show the three buttons `Create`, `Reload` and `Home`. After increasing the window's hight, I can now see these buttons. Maybe you want to make the initial window higher.
- The `Create` button takes me to the page http://www.radio-browser.info/gui/#. Maybe it should take me directly to http://www.radio-browser.info/gui/#/add. Or even make a mask and send the result to radio-browser.info (if their API allows for it).
- In the beginning I wanted to add a station locally (just on my computer), but I can see the point of making it compulsory of adding it to radio-browser.info!

**Comment by haecker-felix** [comment]
Everything already implemented for gradio 6. (except local radio station)
