### ISSUE TITLE
[Feature] Export library as m3u playlist 

### ISSUE THREAD

**Issue by paulcarroty** [haecker-felix/gradio#202]
I think this feature will be very helpful if you use more than one device, especially mobile. Also for `deb/rpm <-> flatpak` migration.

**Comment by haecker-felix** [comment]
Hm what do you mean with m3u playlist? Gradio doesnt create a playlist.

Whatever package format you are using, the database will always be saved in /home/user/.local/share/gradio/.

Anyway in the next version (gradio 6), you can import/export the database in the settings.

**Comment by paulcarroty** [comment]
@haecker-felix I need to hear the Gradio's stations on smartphone. I need to use a paper with pencil to move them? And type the all 10/20/100 stations on virtual keyboard?

**Comment by haecker-felix** [comment]
well you could use this smartphone app: 

https://play.google.com/store/apps/details?id=net.programmierecke.radiodroid2

It is using the same DB as gradio.

**Comment by paulcarroty** [comment]
Can this app recognize the gradio's binary db? I'm not sure.

**Request:** let a user to backup his collections to m3u playlist.
