### ISSUE TITLE
No support for low resolution displays

### ISSUE THREAD

**Issue by baimafeima** [haecker-felix/gradio#203]
I cannot use gradio because the default window size doesn't fit onto my screen. This is one of the rare cases where this happens, usually I can run any programme just fine. My screen resolution is: 1024 x 768.

**Comment by haecker-felix** [comment]
Is already fixed. The next version of gradio has a new layout, which is way more flexible.

**Comment by baimafeima** [comment]
Awesome, that is great news! Thanks a lot!
