### ISSUE TITLE
arrangement of widgets in sort popover menu proposal

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#204]
... as usual, ;-) ,  not an issue but  just  a  proposal about to re-arrange widgets in the sort popover  and maybe reduce width of popover itself.
here my proposal: 
![reviewed sort_popup](https://user-images.githubusercontent.com/296922/30241262-43a6770e-9580-11e7-8684-fe0bebab5f28.png)
currently i.m.o. there is  a lot of empty space  in the popover and at least for me looks weird...

Thanks

**Comment by haecker-felix** [comment]
I would realign the radio buttons, if i would know how....

**Comment by haecker-felix** [comment]
![grafik](https://user-images.githubusercontent.com/6001248/31622093-bda64bdc-b29b-11e7-8f72-782df2bbd90f.png)
