### ISSUE TITLE
Saavn.com and Gaana.com for Indian music

### ISSUE THREAD

**Issue by meetdilip** [haecker-felix/gradio#206]
Any chance to get Indian online radios into this app ? India has around 20 popular regional languages other than Hindi. saavn.com and gaana.com are two popular free music services that offer regional playlists.

**Comment by haecker-felix** [comment]
With the latest Version of Gradio (6.0) you can create new stations with Gradio itself. Also you can add a new station, on this webpage (the database of Gradio): 

http://www.radio-browser.info/gui/#/add
