### ISSUE TITLE
Headerbar menu is duplicated when running in non-CSD environment

### ISSUE THREAD

**Issue by actionless** [haecker-felix/gradio#208]
Steps to reproduce:
1) run bare Openbox (or other WM) without running any gnome-settings-daemon and so on
2) observe top-left corner

Expected result:
in every GTK+3 app i've tried the application menu was residing exclusively under it's icon (which is not visible when running under GNOME):

![2017-09-12--1505243025_148x194_scrot](https://user-images.githubusercontent.com/1655669/30343677-ad5eba14-97fe-11e7-9f74-127212cb2ae1.png)
![2017-09-12--1505243282_255x376_scrot](https://user-images.githubusercontent.com/1655669/30343684-b4edfcb8-97fe-11e7-8694-1a6605e69174.png)

Actual result:
in gradio both application icon and single menu appearing and containing the same menu inside:

![2017-09-12--1505243009_225x240_scrot](https://user-images.githubusercontent.com/1655669/30343690-b9eba49a-97fe-11e7-93f5-d9711414e776.png)
![2017-09-12--1505243303_225x387_scrot](https://user-images.githubusercontent.com/1655669/30343796-0a672ee4-97ff-11e7-8459-f569e380eabd.png)
![2017-09-12-210849_3840x2160_scrot](https://user-images.githubusercontent.com/1655669/30343798-0bde2fe8-97ff-11e7-8512-be8938da3a54.png)

**Comment by actionless** [comment]
thanks!

**Comment by actionless** [comment]
oh, i've just noticed it's still duplicated, but this time in a different place:

![2017-09-17--1505661495_277x430_scrot](https://user-images.githubusercontent.com/1655669/30522202-8c448314-9bcc-11e7-827b-d9af6d253e7a.png)
![2017-09-17-171843_3840x2160_scrot](https://user-images.githubusercontent.com/1655669/30522203-8dab35e0-9bcc-11e7-8dfc-8dc242dc3ce9.png)

**Comment by haecker-felix** [comment]
Damn it 😄

**Comment by actionless** [comment]
thanks! not it's finally alone
