### ISSUE TITLE
HTML characters not decoded

### ISSUE THREAD

**Issue by flipflop97** [haecker-felix/gradio#209]
In the description box, some HTML encoded characters are displayed incorrectly (' as `&#039;` and & as `&amp;`). Examples where this happens are respectively *NPO Soul & Jazz (Radio 2 NL)* and *Radio 538*.

While writing this I also noticed *NPO Soul & Jazz (Radio 2 NL)* had no title being displayed in the search list, probably caused by `&amp;` not being displayed correctly.

Arch Linux  
Gnome 3.24.2  
gradio 6.0 (AUR)

**Comment by dasnoopy** [comment]
Just to confirm that  the title is not displayed for all station with "&" char  in their name ( tried to perfom a simple search  using "&" char  as keyword...
