### ISSUE TITLE
gradio snap should use opengl interface

### ISSUE THREAD

**Issue by ogra1** [haecker-felix/gradio#212]
When starting gradio (using rev 10 from the edge channel) it calls gst-plugin-scan, that will cause gstreamer to also scan for non-audio plugins and produce a message in syslog like:

`Sep 14 12:03:11 anubis kernel: [1028637.574973] audit: type=1400 audit(1505383391.368:49321919): apparmor="DENIED" operation="open" profile="snap.gradio.gradio" name="/var/lib/snapd/lib/gl/libGL.so.1.0.0" pid=16091 comm="gst-plugin-scan" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

adding the opengl interface will allow read access to /var/lib/snapd/lib/gl/ and quieten this message

**Comment by haecker-felix** [comment]
Can you try it with rev 11? I enabled opengl in the snapcraft.yaml.

**Comment by ogra1** [comment]
yup, that fixes the message ...
