### ISSUE TITLE
not connected to m3u8 stream

### ISSUE THREAD

**Issue by lcrippa** [haecker-felix/gradio#213]
I experienced bug #164, the stream was playing with the error message. After the fix, I can't connect to the station anymore (http://radio24-lh.akamaihd.net/i/radio24audio2_1@380795/master.m3u8). Reverting to the old program version the station plays (still displaying the error message though).

EDIT: the problem seems to be in gradio-audio-player.vala, in the portion

```
case Gst.MessageType.ELEMENT:
	state = Gst.State.NULL;

	// TODO: Improve the handling of missing codecs.
    	if(m.get_structure() != null && Gst.PbUtils.is_missing_plugin_message(m)) {
    		status_message = "A required codec is missing.";
    		codec.install_missing_codec(m);
    	}

			break;
```
a quick fix for my specific case is simply to remove the code above

**Comment by sispus** [comment]
version 6.0.1 also won't play m3u8 streams. 
I don't know how to "revert" to the old one as @lcrippa did.

**Comment by lcrippa** [comment]
I would suggest you delete the aforementioned lines from gradio-audio-player.vala and compile from source using cmake (it's a crude solution because it suppresses the "missing codec" warning, but for the time being it works and you don't lose all the new features in version 6)

**Comment by sispus** [comment]
Thank you, @lcrippa 
I have already tried to compile it from the source, but I'm not good at compiling issues, and could not be successfull on it. Thanks to @haecker-felix, flatpak solution is rather preferable for me, but I don't know what's going on while installing by flatpak actually :) I think I will wait a fixed "flatpak version" for listening my favourite turkish radio "trt radyo 3" through my favourite gradio software :)
