### ISSUE TITLE
What happened to the repository ppa:haecker-felix/gradio-daily? I am now getting errors?

### ISSUE THREAD

**Issue by phd21** [haecker-felix/gradio#216]
Hi gradio,

Thank you for a wonderful application.

What happened to the repository ppa:haecker-felix/gradio-daily? All of a sudden I am now getting update GPG Key errors and the PPA is no longer accessible through launchpad???

Best regards to you and yours,
Phil
phd21

**Comment by haecker-felix** [comment]
The PPA no longer exists and is no longer supported. I only maintain the flatpak and snap version from now on. Maybe someone will create a new PPA, but not me. 

More Information:
https://github.com/haecker-felix/gradio/wiki/Install-Gradio
