### ISSUE TITLE
Station discovery is worse than before

### ISSUE THREAD

**Issue by baimafeima** [haecker-felix/gradio#219]
The new user interface fits onto my screen as opposed to the previous one but now the great overview over lots of stations is gone and generally station discovery and easy of use of the application have deteriorated.

**Comment by haecker-felix** [comment]
Okay, I have to admit the discovery function has deteriorated. That was not my goal. Actually, I wanted to improve it....
Anyway, I'm trying to restore the old discover principle in the next update .

Overall, the usability should not have deteriorated. Or what exactly has gotten worse now? I'm open to suggestions!

**Comment by baimafeima** [comment]
Thanks for being open to experiment, this is a great virtue. The old discovery principle was really great. What has gotten more difficult is the process of how to add stations. More clicks are necessary, probably related to the missing discovery interface.

**Comment by haecker-felix** [comment]
![bildschirmfoto vom 2017-10-12 21-13-30](https://user-images.githubusercontent.com/6001248/31514614-7813b8f4-af92-11e7-9272-939e58569637.png)


Well, this should 'fix' this issue 😄
