### ISSUE TITLE
Gradio-daily ppa not found

### ISSUE THREAD

**Issue by vician** [haecker-felix/gradio#220]
Hi,

I don't know what happened but ppa for gradio daily build is not available anymore, see https://code.launchpad.net/~haecker-felix/+archive/ubuntu/gradio-daily and http://ppa.launchpad.net/haecker-felix/gradio-daily/ubuntu

It would be great if this could be fixed. I tried snap instead of ppa, but it needs gnome-3.24 which I don't use.

Thank you!

**Comment by GAJansen** [comment]
Same here, no gradio-daily PPA found.
Is this on purpose, or did the removal happen by accident? Would be great to restore the PPA.
Thanks in advance!

**Comment by sispus** [comment]
Maybe you can give flatpak a try.

**Comment by haecker-felix** [comment]
The PPA no longer exists and is no longer supported. I only maintain the flatpak and snap version from now on. Maybe someone will create a new PPA, but not me.

More Information:
https://github.com/haecker-felix/gradio/wiki/Install-Gradio

**Comment by raphaelh** [comment]
Hi Felix,

first of all thanks for your great app!

Could you explain briefly why you choose to drop PPA support in favor of flatpak and snap?

I purge the .deb package before installing the new flatpak, it told me it was freeing **506 kb** of disk space

I then installed flatpak which is using **5 471 kb** of disk space, then gradio's flatpak which is using **197 MB** (only 3 MB for gradio and 1 MB for gradio locale, the rest being org.gnome.Platform)

With snap, it's **37 MB** for gradio and **135 MB** for gnome-3-26-1604, **172 MB** in total

**Comment by haecker-felix** [comment]
I do not want to start a big debate here, so the answer in short: Snap and Flatpak have their advantages and disadvantages. 

The Flatpak Basic Runtime is quite large, but you install it once (and not for every application).
Nowadays, storage space shouldn't be a big problem anymore.

Users who still want to use Gradio as debian package can use an external package source. For example http://www.getdeb.net/software/gradio
