### ISSUE TITLE
feature : move collection folders in the library

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#221]
first of all, thank you for that "collections"! a very good step forward :)
it wold be good to have the collection folders among the 'non-collectioned' single stations under library tab (and not to have the stations already added a collection). 
(by the way, station skip by back-forward buttons is very cool, too!)

**Comment by haecker-felix** [comment]
![grafik](https://user-images.githubusercontent.com/6001248/30859000-31e350ce-a2c2-11e7-8674-b724fe6c4d08.png)

Work in Progress :-)

This requires a lot of changes under the hood, so this feature will be released with Gradio 7.0

**Comment by haecker-felix** [comment]
Done. Already on master.
