### ISSUE TITLE
feature : five-star local "favorite" tagging and sorting

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#222]
It would be good to have an opportunity to give stars (maybe also half-stars, e.g. 3½ star) locally to the stations, and to sort them also according to their stars. (for 6.0.1)

or, custom sorting? but i couldn't imagine a convenient way for that.

**Comment by haecker-felix** [comment]
A five star tagging would be hard to implement, but you can sort stations into groups/collection. 
In version 7.0 the sorting options have also been greatly improved.

Personally, I do not think a 5 star system is very useful, it would overlap with the voting system.
