### ISSUE TITLE
feature : flexible number of columns

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#223]
I really like gradio, so I think I deserve a self-indulgence for too much feature requests :) sorry for that.

Now the stations are presented in a kind of containers divided into three columns. When we change the width of the gradio window or the size of the station icons, their width also change (or for the latter, remain fixed) up to preserve "three-column" structure. However, it would be better if the columns structure to be flexible, that is, to change to allow four or five columns, or even two or one column, according to size of the station icons or the width of the gradio window.

**Comment by haecker-felix** [comment]
The columns are already flexible?

![gradio_layout](https://user-images.githubusercontent.com/6001248/30816254-b78228ac-a215-11e7-8fec-d4f53ca9c140.gif)

**Comment by sispus** [comment]
well, yes, apparently :) and looks handsome. but still, for me it is not. 
i tried to uninstall, remove the folder in .var/app and reinstall it on opensuse 42.3 with kde plasma 5.8.7, same result.
