### ISSUE TITLE
GStreamer Plugins

### ISSUE THREAD

**Issue by swinkl3** [haecker-felix/gradio#23]
You should add a note to the dependencies to install gstreamer-plugins or whatever the package is called in each distro. Even though some streams will play, many won't and GRadio will pop an error saying that Your GStreamer installation is missing a plugin.

**Comment by mauriciobaeza** [comment]
![gradio](https://cloud.githubusercontent.com/assets/636253/17232649/317335c2-54ef-11e6-96f2-15253e1e9bb9.png)

but, I listen audio mp3 correctly...

**Comment by haecker-felix** [comment]
Okay this behavior isn't perfect. I'll improve this. (Like showing _which_ gstreamer package is missing)

**Comment by TingPing** [comment]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-gstpbutilsmissingplugins.html

**Comment by haecker-felix** [comment]
Fixed.
