### ISSUE TITLE
Use grilo for browsing and searching

### ISSUE THREAD

**Issue by hadess** [haecker-felix/gradio#232]
Rather than implement browsing and searching the radio-browser.info website directly, this could be implemented as a grilo plugin (probably in lua), so as to make it easier to swap out the service for another one, and make this service available in other applications which use Grilo, such as Rhythmbox.

An example radio plugin is available at:
https://git.gnome.org//browse/grilo-plugins/tree/src/lua-factory/sources/grl-radiofrance.lua

Look for the "radio" tag.

**Comment by haecker-felix** [comment]
At the moment I don't see any advantage for Gradio itself why I should use grilo. The backend is not going to be swapped out either, because Gradio is supposed to be a client for radio-browser.info.

This may sound stupid, but this is currently too much work for no big advantages.
