### ISSUE TITLE
Closing the gui does not stop the process

### ISSUE THREAD

**Issue by dino99** [haecker-felix/gradio#234]
I'm a gradio fan since a while, on ubuntu amd64 (artful now, gnome-shell & wayland session), firstly using your launchpad ppa, then ppa:chronitis/misc, and now a cli flatpak 6.0.2 install.

Before the 6 th version, closing the gui was also killing the process, as expected. Now with both 6.01 (ppa) & 6.02 (flatpak) the reading/playing process continue after the gui has been closed, which is not expected. The process has to be killed via htop or else.
Hopes this will be fixed to get friendly experience.

Thanks for that great app.

**Comment by haecker-felix** [comment]
App -> Settings -> Background Playback -> OFF

**Comment by dino99** [comment]
Thanks for the answer, but i cant find such App menu settings. I remember the 5 version was offering many features (like, popover, ...) but that 6 is minimalist. The details explain for the 5th version mainly. Do i need to add a dependency to get that missing appmenu?
