### ISSUE TITLE
Some entries are disabled in the popover application menu...

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#236]
...may be is related to #235 but  since  commit https://github.com/haecker-felix/gradio/commit/e54e3a674d29043cd1123593368d879177860a57, in the popover application menu following entries are disabled:

- Settings
- About 
- Exit

(gradio compiled from source on Archlinux 64bit)

Regards

**Comment by haecker-felix** [comment]
Should be fixed now.
