### ISSUE TITLE
Please, What are the exact instructions for compiling this from source code?

### ISSUE THREAD

**Issue by phd21** [haecker-felix/gradio#237]
Hello haecker-felix/gradio,

First, thank you for providing this wonderful streaming radio application.

Could you Please provide the exact instructions for compiling this from source code on a Linux Ubuntu computer? I am using Linux Mint KDE 18.2 (Ubuntu 16.04). Need to know what compiling dependencies need to be installed first as well, please.

Best regards to you and yours,
Phil
phd21

**Comment by haecker-felix** [comment]
glib, gtk3 3.22.6, libsoup, json_glib, gstreamer, gstreamer_pbutils, sqlite3

meson . build
cd build
ninja 
sudo ninja make install
