### ISSUE TITLE
Gtk theme not apply - dark theme not working

### ISSUE THREAD

**Issue by armageddon51** [haecker-felix/gradio#239]
Just install version 6.02 with a flatpak. First foray into this. Not obvious. After 250 MBytes of download. No menu entry was created. I had to search the internet on how to start Gradio. Here it is.
> flatpak run de.haeckerfelix.gradio/x86_64/stable

Obvious. Why is this not in the gradio github page ?

Anyway, I noticed that the application ignore the GTK theme used and dark theme selector does not work. Is that  a deficiency of flatpak ou something missing in Gradio ?
Tx

Xubuntu 17.10

**Comment by armageddon51** [comment]
After learning more about flatpak, there are now flatpak themes available to install as is. Applications can then use it, so does Gradio !!!!
Tx

**Comment by haecker-felix** [comment]
There should be a Gradio starter in your desktop menu, otherwise it is a bug of flatpak. The app starter should be there after a restart of your PC.

And yes you need to install your gtk theme as flatpak as well. This isn't a issue of Gradio itself.
