### ISSUE TITLE
Feature Request: Potentially allow an input of an FM Number?

### ISSUE THREAD

**Issue by feren** [haecker-felix/gradio#24]
Pretty much self-explanatory, for example, if you want to listen to Heart Cambridgeshire 102.7 FM, you can only find the London heart and listen to that, so is it possible to make an option to listen to a station by using their FM number to find their station??

**Comment by haecker-felix** [comment]
No this isn't possible. Gradio use internet streams. To enter the FM number manually you need a physical radio card.
