### ISSUE TITLE
How to delete a radio station that won't work

### ISSUE THREAD

**Issue by affinityv** [haecker-felix/gradio#241]
I tried to add a radio station, but whilst I can edit the "title", I cannot edit the stream URL.

Nor can I remove it now.

This is the [current] name:
PLEASE DELETE -- broken -- Best Net Radio - Golden Oldies

It's URL come from VLC / Icecast Radio
http://113fm-edge2.cdnstream.com:80/5159_128

**Comment by affinityv** [comment]
Looks like someone has edited the entry and it is working now.  The stream address field needs to be able to be copied from and/or expanded in size to see the entire URL.  And why isn't that field editable?

**Comment by haecker-felix** [comment]
The stream input field cannot be edited unless the station is broken. This is a spam protection that prevents the functioning sender from being edited.

You shouldn't delete a station. You should edit it, and make it working ;)

Anyway, full database access:
http://www.radio-browser.info/gui/#/topclick

Here you can do anything.
