### ISSUE TITLE
Gradio application (snap package) does not initialize

### ISSUE THREAD

**Issue by erickmajor** [haecker-felix/gradio#245]
## Expected Behavior
The app should initialize properly after clicking the icon located in the Applications Menu.

## Current Behavior
When clicking on the icon of the application, located in the Applications Menu, it does not open, finishing without any window of information of the happened one.

## Steps to Reproduce
Opening the application by the graphical environment:
1. Click the application icon, located in the Applications Menu;
2. The wait cursor appears, indicating the application initialization;
3. The cursor returns to its normal state (arrow) and there is no demonstration of error.

Opening the application by the terminal:
1. Open the system terminal;
2. Type in the user terminal ```gradio```;
3. After a few seconds, the terminal returns the following error: ```(gradio:2787): Gtk-WARNING **: cannot open display: :0```. 

## Detailed Description
Terminal data:
```
~$ gradio
** Message: gradio-app.vala:188: Gradio 6.0.2 
** Message: gradio-app.vala:196: Locale dir: /snap/gradio/current/usr/share/locale

(gradio:2787): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(gradio:2787): Gtk-WARNING **: cannot open display: :0
```
Version: 6.0.2.
SO: Linux Ubuntu 17.10.

**Comment by haecker-felix** [comment]
How did you install the snap? Don't forget to connect the snap:


_sudo snap install gnome-3-24_ 

and then:

_sudo snap connect gradio:gnome-3-24-platform gnome-3-24:gnome-3-24-platform_ 

And then try again.

**Comment by erickmajor** [comment]
Hello @ haecker-felix,

I installed it several times. First I made the installation using the Ubuntu application store, then via terminal. In the terminal installation, I connected the gradio with the gnome-3-24-platform, as you specified me at the moment.

In both cases the error presented is the same.

**Comment by erickmajor** [comment]
Additional Information: I believe the error happens due to the version of gnome installed on this version of Ubunto, which is Gnome Shell 3.26.

**Comment by haecker-felix** [comment]
Issue is found, a fix is going to be released soon.

**Comment by haecker-felix** [comment]
Fix it released. Don't forget to:

`snap refresh`

Now everything should work fine. Thanks for you bug report.

**Comment by erickmajor** [comment]
Thank you @haecker-felix!

I checked before upgrading and it really worked in the Xorg environment. I upgraded the application and it worked in both environments (Wayland and Xorg).

Thanks for the quick fix!
