### ISSUE TITLE
Several messages are not translated in the GUI even though they exist in translation

### ISSUE THREAD

**Issue by Faenriis** [haecker-felix/gradio#247]
Several strings are displayed in English (source language) even though translations exists.
I'll provide images as it'll be easier to explain where they are.

1. "Library" when it's a window title
https://imgur.com/a/f3613

2. "Settings" window title
https://imgur.com/a/TmK1o

3. "Click on items to select them"
https://imgur.com/a/a6AeN

4. Multipe strings in Search dialog
https://imgur.com/a/HMh5i 

5. I believe that list of languages and and countries/regions was intended to be taken from GTK/Gnome libraries, however it is in untranslated form.
https://imgur.com/a/s18C1

6. "Create new station" window title.
https://imgur.com/a/OaZhw
(I think that it's safe to say that if string is a window title it will not appear translated)

Build I'm using is from current git.

Can it be fixed before release on 19th, please? 
Let me know if I can provide more info/data..

**Comment by Faenriis** [comment]
Oh, while I'm on the subject, can this string be made plural please?

 #: data/ui/details-box.ui:206
 msgid "Items"
 msgstr "stavki"

Even in English it doesn't make sense to see "1 Items" when there's only one station in the library,
for me in Serbian it gets even more complicated (1 stavka, 2 stavke, 5 stavki).

**Comment by erwinvaneijk** [comment]
Faenriis, how does other software handle that? As I understand Serbian works like Russian, where 'one thing' is conjugated differently from '2, 3 or 4 things', which is conjugated differently from '5..20' and where '21 things' is conjugated like 'one thing'. Do other software packages deal with it at all in translations?

**Comment by Faenriis** [comment]
It's Gettext that deals with it (as it does in all software based on glibc).
https://www.gnu.org/software/gettext/manual/html_node/Translating-plural-forms.html
Now, I'm not a coder, unfortunately, so I'm not sure how it's defined in code exactly, but will look into it and notify you.

**Comment by erwinvaneijk** [comment]
Thanx!

**Comment by Faenriis** [comment]
There is possibly a workaround which should work for all languages, just changing the message to appear in GUI as:

_Items: %d_

should make the plural form unnecessary.
Again, I only _think_ that'll be acceptable in all languages. Making it a proper plural string is certainly better, but if it's too much work for just this tinly little messsage, it's a workaround worth considering.

**Comment by haecker-felix** [comment]
Everything should now be translatable. 

5 -> I cannot change this text. I get this text from the database http://www.radio-browser.info/gui/#/countries

**Comment by Faenriis** [comment]
Thank you, tested it, works.
