### ISSUE TITLE
[suggestion] Join the Gnome project as Gnome-Radio

### ISSUE THREAD

**Issue by Postroutine** [haecker-felix/gradio#248]
Gradio is an awesome application. Why not propose it as Gnome-Radio inside the Gnome project? ;)

**Comment by haecker-felix** [comment]
I wouldn't mind, but I don't think it's very easy.

Does it offer an advantage? Never done anything like this before ^^

**Comment by Postroutine** [comment]
Some advantages:
- Be hosted on the Gnome Project infrastructure
- Be distributed by the Gnome Project as part of their apps
- Possible more integration with other applications
- When you have new features on your app, it will be discussed in the release notes
- Help from the gnome community 

Generally, this mean more highlight on the application and help more people to know your work

**Comment by haecker-felix** [comment]
Sounds pretty nice. I think I have to be a GNOME foundation member. 

I have absolutely no idea how I should do this. I think I have to be a member of the GNOME core Dev team? Idk. 

Is this process already done by a other app? I believe not.

**Comment by haecker-felix** [comment]
I think I need some people from the GNOME Team, who know me. (Which I don't have)

Please don't get me wrong, it sounds pretty nice.

**Comment by Postroutine** [comment]
The Gnome project had a new comer page: https://wiki.gnome.org/Newcomers
But it's for working on apps that already part of Gnome.

Maybe asking on #gnome-hackers IRC channel.

**Comment by haecker-felix** [comment]
Nah i just ask it on the newcommers irc

**Comment by aklapper** [comment]
None of the so-called "advantages" automatically come from being "inside the Gnome project", if I understand correctly. 
It's not that all projects in GNOME Git are "distributed by the Gnome Project as part of their apps". 
You are always free to have "possible more integration with other applications" by writing code, but that does not automatically happen by being "inside the Gnome project". 

This entire discussion feels like a solution in search of a problem. :)

**Comment by haecker-felix** [comment]
There is no "problem", it's just a place to discuss this topic :-) I'm assuming that it won't really be possible, as I imagined. Anyway, thanks for the info.
