### ISSUE TITLE
desktop-file-validate fails on desktop-file

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#25]
When running desktop-file-validate on gradios desktop-file it fails with following errors:

> + desktop-file-validate /builddir/build/BUILDROOT/gradio-4.0-1.201607281820git366b15d.fc24.x86_64/usr/share/applications/gradio.desktop
/builddir/build/BUILDROOT/gradio-4.0-1.201607281820git366b15d.fc24.x86_64/usr/share/applications/gradio.desktop: error: value "4.0.0" for key "Version" in group "Desktop Entry" is not a known version
/builddir/build/BUILDROOT/gradio-4.0-1.201607281820git366b15d.fc24.x86_64/usr/share/applications/gradio.desktop: error: file contains key "_Comment" in group "Desktop Entry", but key names must contain only the characters A-Za-z0-9- (they may have a "[LOCALE]" postfix)
/builddir/build/BUILDROOT/gradio-4.0-1.201607281820git366b15d.fc24.x86_64/usr/share/applications/gradio.desktop: error: file contains key "_GenericName" in group "Desktop Entry", but key names must contain only the characters A-Za-z0-9- (they may have a "[LOCALE]" postfix)
/builddir/build/BUILDROOT/gradio-4.0-1.201607281820git366b15d.fc24.x86_64/usr/share/applications/gradio.desktop: error: value "GNOME;GTK;Utility;Productivity" for key "Categories" in group "Desktop Entry" contains an unregistered value "Productivity"; values extending the format should start with "X-"

**Comment by haecker-felix** [comment]
Fixed.
