### ISSUE TITLE
Search engine doesn't return all tagged stations for a given keyword. 

### ISSUE THREAD

**Issue by marcelopm** [haecker-felix/gradio#250]
Take for instance the stations tagged with the keyword "samba":

![image](https://user-images.githubusercontent.com/1010930/33589112-6364dc58-d9c2-11e7-97be-6ee8247a70d0.png)

When searching for that same keyword, only a few of the all tagged stations are returned:

![image](https://user-images.githubusercontent.com/1010930/33589149-8ec91422-d9c2-11e7-8297-66cd67c8d79b.png)

## Expected Behavior

The search result should contain all stations tagged by the searched keyword.

## Current Behavior

Only a few of the tagged stations are returned:

![image](https://user-images.githubusercontent.com/1010930/33589149-8ec91422-d9c2-11e7-8297-66cd67c8d79b.png)

## Steps to Reproduce

1. Click in tags
2. Select samba
3. Check results
4. Type samba on the search box
5. Hit enter
6. Check results (different than item \#4)

**Comment by haecker-felix** [comment]
You are using version 5.0 of Gradio. Please update Gradio. The current version is 6.0.2 (and soon 7.0)

**Comment by marcelopm** [comment]
Hum ok, I thought I had the latest stable one as I followed the installations instructions from here:

https://github.com/haecker-felix/gradio/wiki/Install-Gradio
