### ISSUE TITLE
weird search results for "Stations with the most clicks"

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#255]
After recent commits, In dIscover  page , if I press the **More** button for "Stations with the most clicks"  the search results produces a weird list (see the attached image) : mostly of result are about Russian radios with few clicks...

![gradio](https://user-images.githubusercontent.com/296922/33818455-52558d54-de45-11e7-96db-bf6931ab9b7f.png)

Thanks

**Comment by erwinvaneijk** [comment]
I've looked into it, and created a PR that should address this.

**Comment by haecker-felix** [comment]
Thanks for @erwinvaneijk for the solution.
