### ISSUE TITLE
Enable search by tags

### ISSUE THREAD

**Issue by erwinvaneijk** [haecker-felix/gradio#259]
It would be cool if you can search the stations by using the tags that are present in the radio-browser api.

## Expected Behavior

The use can search for stations by the tags that are applied to them. Either by entering the tag in the search window, or by clicking on the tag, which is pointer to a collection of radio stations.

**Comment by haecker-felix** [comment]
Currently there are 4950+ tags available. Many (!) contain two stations or less. I would have to fetch the complete list of all tags, which means Gradio would create 4950+ gtk labels, which would drastically increase the memory usage.

I have to rework the current filter popover, but not for Gradio 7.0.

**Comment by erwinvaneijk** [comment]
Yes, I've noticed that, that's why I was thinking about implementing a 'completion' feature, instead of just dumping all them tags on the screen.
