### ISSUE TITLE
Debian 8 can't install

### ISSUE THREAD

**Issue by DavidLatorre90** [haecker-felix/gradio#26]
This can't be compiled on Debian 8 kernel 4.4
Why?
Gtk 3 Version 3.18 is a testing version, the stable version is 3.14 in Debian.

I think this aplication was developed based on Ubuntu last version, I consider that we must develop based on Debian, the parent distro becasuse Debian use the last stable and secure libraries, Ubuntu must not be the center of the aplications development this has a lot of bugs and unsecure and testing libraries like the gtk3 3.18.

it's just a suggestion

**Comment by haecker-felix** [comment]
Gradio requires GTK 3.18. Sorry i cannot change that.

**Comment by haecker-felix** [comment]
@DavidLatorre90 but i'm planing to ship gradio as a flatpak. Then it should be possible ;)
