### ISSUE TITLE
Display codec and bitrate

### ISSUE THREAD

**Issue by sphh** [haecker-felix/gradio#261]
## Expected Behavior

The codec and bitrate of the selected radio station should be displayed in the following views:

- Details
- Search
- Library (maybe configurable)
- Statusbar (maybe configurable)

## Current Behavior

Neither the codec nor the bitrate of the selected radio station is displayed.

## Detailed Description

Often a radio station provides multiple streams, such as Radio Paradise or Deutschlandfunk and others. Currently it is not possible to distinguish between the different streams, if the submitter did not add this information to the title. Showing the codec and bitrate would help the user to pck the stream most suitable for his/her needs.

**Comment by haecker-felix** [comment]
In the next version of Gradio, you can choose whether to display technical information or not.

![grafik](https://user-images.githubusercontent.com/6001248/34467158-49c1c7d4-eee9-11e7-87db-04bf3ca398b6.png)

![grafik](https://user-images.githubusercontent.com/6001248/34467139-d1ecfdfa-eee8-11e7-994a-2027c7694e89.png)

![grafik](https://user-images.githubusercontent.com/6001248/34467144-0fadccfa-eee9-11e7-8adf-70d6023414ef.png)

**Comment by sphh** [comment]
Thanks. That looks perfect.

Happy new year!
