### ISSUE TITLE
Search by country

### ISSUE THREAD

**Issue by enovision** [haecker-felix/gradio#263]
I believe that in version 5 you could search by country. 

In version 7 I can't figure a way out to find all broadcasting stations from f.e. the Netherlands.
It would be nice to have a country filter, to narrow the search only to a selected country.

**Comment by haecker-felix** [comment]
Search Page -> Button next to search entry (Arrow Down) -> Select your country

**Comment by enovision** [comment]
@haecker-felix, thank you, I completely missed that option. I thought it was to confirm (Enter) the search argument in the search field.
