### ISSUE TITLE
Support for cinnamon sound application icon?

### ISSUE THREAD

**Issue by orschiro** [haecker-felix/gradio#266]
Dear all, 

I am wondering if we can provide a dedicated Gradio icon to be used in the sound application menu of the Cinnamon DE? Having a dedicated icon definitely helps to quickly find Gradio among the apps if you have multiple running.

Thank you!

![image](https://user-images.githubusercontent.com/170947/34455506-e93bc72a-ed80-11e7-8370-8a5206a91394.png)

**Comment by haecker-felix** [comment]
![grafik](https://user-images.githubusercontent.com/6001248/34455605-9d2cf406-ed82-11e7-882e-e7da93281a6a.png)

In gnome control center the icon is missing too. I think it's the same icon, which is missing.

**Comment by haecker-felix** [comment]
![grafik](https://user-images.githubusercontent.com/6001248/34455902-7027a26a-ed89-11e7-8bde-cc9da22e2e8c.png)

Looks better now! Code is already on master.

**Comment by orschiro** [comment]
Just brilliant.
