### ISSUE TITLE
Gradio 7 flatpack on lubuntu without sound

### ISSUE THREAD

**Issue by Ilford125** [haecker-felix/gradio#271]
fresh installed flatpack of current version 7 has no sound. Audacious, Rhythmbox etc. all working well, but gradio keeps silent.
## Expected Behavior

After connecting to a station I should hear sound.
## Current Behavior

After connecting to a station the stream is coming in but I cannot hear anything. Sound is on full level on netbook as well as on gradio application. Every other sound app produces sound, not gmail.
## Detailed Description

I am running an up to date Lubuntu on an old one core netbook as my internet radio. Until now I had gradio 4 running, installed vial .deb package. Purged the package, installed flatpack according to the howto on omg ubuntu (http://www.omgubuntu.co.uk/2017/12/gradio-7-0-radio-player-for-linux):

1. sudo apt install flatpak
2. flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
3. sudo flatpak install flathub de.haeckerfelix.gradio

Did I miss anything? It is my first flatpack I ever installed, used to install by using apt with .deb packages.

And last but not least: Thank you for taking your time to build this great app!

**Comment by orschiro** [comment]
I think I am experiencing the same issue on Linux Mint 18.3 Cinnamon. I press play, the interface shows it is playing, I do have internet but I am not hearing any sound.

![image](https://user-images.githubusercontent.com/170947/34601300-9f07a14a-f1fb-11e7-83fa-9b8042a5e6b2.png)

**Comment by orschiro** [comment]
Hmm, this is definitely not a consistent issue. I rebooted and have sound again. Works without a problem at the moment. Will report back if I re-encounter the problem.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by haecker-felix** [comment]
Please send the terminal output, if the issue occurs. It might be a flatpak issue.

**Comment by Ilford125** [comment]
Hi, sorry for the late reply, but I was offline for some time. I started gradio in xterm and this is the output:

```
$ flatpak run de.haeckerfelix.gradio 
** Message: gradio-app.vala:178: Gradio 7.0 
** Message: gradio-app.vala:186: Locale dir: /app/share/locale

** (gradio:2): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
** Message: gradio-app.vala:128: Registered search provider service.
** Message: gradio-app.vala:121: Desktop session is: Lubuntu
** Message: gradio-library.vala:75: Open database...
** Message: gradio-library.vala:76: /home/mik/.var/app/de.haeckerfelix.gradio/data/gradio/gradio.db
** Message: gradio-library.vala:46: Successfully opened database! Reading database data...
** Message: gradio-main-window.vala:271: Changed page mode to "library"

(gradio:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(gradio:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
** Message: gradio-audio-player.vala:83: Connecting to: http://198.15.94.34:8006/stream
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
``` 
Maybe this can help. Thanks again for your support and your time! And gradio!

**Comment by haecker-felix** [comment]
Huh, why i sent the same message so often?? This was not intended!!

Howevery, this looks like a flatpak issue. I cannot reproduce it.  
I recommend you to open a Flatpak Issue. Please include the terminal output to the issue, it's important.

**Comment by orschiro** [comment]
Just to let you know that I haven't had any issues lately. ☺

**Comment by haecker-felix** [comment]
maybe a flatpak update fixed this :-)

**Comment by Ilford125** [comment]
Hi Felix,

todays update on lubuntu fixed the issue. Gradio is great, now my stoneages netbook is able to still work as a webradio again! Thanks so much!
