### ISSUE TITLE
RFE: provide a 'repeat' and 'previous' button that works for streamed radio

### ISSUE THREAD

**Issue by i30817** [haecker-felix/Gradio#274]
It seems a interesting concept, that would first require dumping memory streams to local memory so they could be rewinded.

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description
Button to lock the current song to repeat, or to go back to the previous song (optionally more than one?). These interfaces wouldn't have anything to do with MPRIS and other similar standards, that still are better served by mapping to radio station switching.  This idea only works if the radio station announces 'when' a song starts, and maybe the the size of it (to not save to memory unreasonably sized streams). I don't know if internet radio is that sophisticated.

If it's possible, feature is similar to the proposed ability to record the stream (needing additional markers of song end and start to jump back, and probably not try to jump back to a 'incomplete' stream - that doesn't start from the beginning), so it's probably better to design both at once?

**Comment by haecker-felix** [comment]
Currently not supported. Gradio will support radio recording soon, maybe I can add this then.
