### ISSUE TITLE
Improve graphical installation instruction

### ISSUE THREAD

**Issue by orschiro** [haecker-felix/gradio#275]
Dear all,

I am refering to the [wiki](https://github.com/haecker-felix/gradio/wiki/Install-Instructions#graphical) wher eit says:

> Graphical:
> Click here to install Gradio

However, this is not clear (at least to me). If I click the link on Linux Mint 18.3 Cinnamon, it downloads the `.flatpakref` file. If I open this file, it opens it inside a text editor. No way to install it graphically. 

What else is needed and should be mentioned on the Wiki?

**Comment by phw** [comment]
Currently I only know for sure this is supported by GNOME Software, so this needs to be available. KDE Discover [made some progress with Flatpak support](http://www.jgrulich.cz/2017/02/14/kde-discover-flatpak-backend/) (including .flatpakref files), but I am not sure this is already readily available somewhere. At least in my KDE Neon VM it does not yet seem to work.

Related discussion might also be https://github.com/flatpak/flatpak/issues/859 , also the Flatpak team currently have no plans to implement a simple GUI themselves.

**Comment by orschiro** [comment]
I tried an open with GNOME Software (3.20.5-0ubuntu0.16.04.7) right mouse click on the flatpakref file but only got this:

![image](https://user-images.githubusercontent.com/170947/34605213-0804fada-f20b-11e7-9e5b-b4367e68f5b4.png)

**Comment by phw** [comment]
Just an update on KDE Discover: I tested again on my KDE Neon VM and it is fully working, you just have to install `apt install plasma-discover-flatpak-backend`.

@orschiro Given that Gnome Software 3.20 was AFAIK the first release supporting Flatpak I am not surprised. Flatpak support was bugged back then, but has matured very well and works quite good in latest version.

**Comment by orschiro** [comment]
> Given that Gnome Software 3.20 was AFAIK the first release supporting Flatpak I am not surprised. Flatpak support was bugged back then, but has matured very well and works quite good in latest version.

@phw good to hear. Wanted to test it but it is too difficult to install any version > 3.20 on Linux Mint 18.3 :-(

**Comment by haecker-felix** [comment]
I've updated the introductions. Thanks for the information!
