### ISSUE TITLE
gradio don't uses GTK theme (adapta)

### ISSUE THREAD

**Issue by thegreatyellow67** [haecker-felix/gradio#276]
Hi, thanks for your great gradio app!

In my fresh Linux Mint 18.3 linux system with xfce I've installed your app using FLATPACK command:
flatpak install --from https://flathub.org/repo/appstream/de.haeckerfelix.gradio.flatpakref

So, I wold like to now if it's possible to give it the same gtk look I'm using (adapta-gtk-theme).

As you can see the look is different:
http://i.imgur.com/zbCoz6u.png

Thanks!

**Comment by phw** [comment]
FLatpak should normally install the theme extension for the used runtime automatically, but probably this did not work (what flatpak version do you have?). Try installing it manually with:

    flatpak install org.gtk.Gtk3theme.Adapta

**Comment by thegreatyellow67** [comment]
Using Flatpak 0.10.0...trying to install Adapta theme...

**Comment by thegreatyellow67** [comment]
Resolved! Thanks! Your command was incompleted, missed "flathub" repo...
Used:
flatpak install flathub org.gtk.Gtk3theme.Adapta-Nokto (that's is my system wide style)
