### ISSUE TITLE
Flatpak (PPA) Ubuntu 16.04 - Dark theme doesn't apply

### ISSUE THREAD

**Issue by silvernode** [haecker-felix/gradio#277]
## Flatpak Version
Flatpak 0.10.2.1

## Desktop Environment  
XFCE 4.12  

## Expected Behavior
Install Flatpak, apply dark theme, see dark theme

## Current Behavior
Install Gradio Flatpak, apply Dark Theme, still see white theme.

## Steps to Reproduce

1. Install flatpak (via repo or PPA)
2. Install Gradio via Flathub Repo (this should work flawlessly)
3. Run Gradio via desktop file or Flatpak commands
4. Set Dark Theme in Gradio

## Detailed Description

I'm not sure what to write here because in Void Linux the Gradio Flatpak is able to set the theme. I know I could probably get it to work by installng a GTK theme via Flatpak but I feel that the Dark Theme should work out of the box.

**Comment by phw** [comment]
This might be theme related, what theme are you using? Does it work if you set the system theme to the default Adwaita?

For me this works with the Adapta and Adwaita themes.

**Comment by silvernode** [comment]
I am using the Adapta Nokto theme.

**Comment by silvernode** [comment]
Changed to Adwaita theme via appearance setting in XFCE and Gradio gracefully applied dark theme without other intervention. Switching to any of the available Adapta themes turns Gradio white again.

**Comment by phw** [comment]
As Adapta-Nokto already is a dark theme that rather indicates it is not using Adapta theme at all. Do you have the flatpak theme extensions (`org.gtk.Gtk3theme.Adapta`, `org.gtk.Gtk3theme.Adapta-Nokto` etc.) installed? If not, install them from flathub.

Newer flatpak versions actually should automatically install the extensioin for your currently active GTK theme if available when you run `flatpak update`. But if it doesn't you have to install it manually, e.g.

    flatpak install flathub org.gtk.Gtk3theme.Adapta-Nokto

**Comment by silvernode** [comment]
```
flatpak search adapta
Application ID          Version Remotes Description                                    
org.gtk.Gtk3theme               flathub Adapta Gtk+ theme                              
org.gtk.Gtk3theme               flathub Adapta-Nokto-Eta Gtk+ theme (dark and compact) 
org.gtk.Gtk3theme               flathub Adapta-Nokto Gtk+ theme (dark)                 
org.gtk.Gtk3theme               flathub Adapta-Eta Gtk+ theme (compact)                
org.gtk.Gtk3theme               flathub Pop Gtk theme used by System76                 
org.gtk.Gtk3theme               flathub Pop Gtk theme used by System76                 
```

That's all I see when I search for adapta. This is the first time it has not shown the Ref name you suggested. I tried to get the flatpak of adapta easier but as you see above something wasn't right.

**Comment by silvernode** [comment]
Installing adapta nokto via Flatpak solved the issue. I still think it should work out of the bix 100% of the time but what can you do? On one hand it works out of the box in some cases and to solve cases where it doesn't then the Gradio team might have to bundle every theme with the flatpak or something. Either that or somehow make other themes work as reliably as the Adwaita system theme works.

**Comment by phw** [comment]
Glad to hear it is working now for you. Yes, if you think there is something not working with how Flatpak installs the themes you should probably open an issue for Flatpak.

**Comment by silvernode** [comment]
I am going to close this issue now since it has been resolved one way or another and could prove to be on the side of Flatpak to begin with. Thanks for the help and your time.
