### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [haecker-felix/gradio#278]
Thanks for making this cool app! I have only one nitpick: the name.

Apps in the GTK/GNOME ecosystem have been moving away from names starting with G for quite some time. The current name makes it sound like an outdated app from the GNOME 2 days, which is hardly a great first impression.

If you're open to changing the name I would be happy to help in brainstorming a new name (and then make a new icon if necessary). Some of the apps I've named/branded recently are [Fractal](https://gitlab.gnome.org/danigm/fractal/) and [Teleport](https://gitlab.gnome.org/jsparber/teleport).

**Comment by haecker-felix** [comment]
I totally agree with you, the name could be better.  But I think it's a bad idea to change the name now, as the program is now known to many as "Gradio". 

But I would be very happy if you could design a logo for "Fragments". The icon of fractal and teleport looks very nice!

Fragments is a new bittorrent client. Still WIP. 
https://github.com/FragmentsApp/Fragments

**Comment by bertob** [comment]
Ok, fair enough.

Great job naming Fragments though, that's an awesome name for a torrent app! I'd be happy to help out with an icon.

Do you have an IRC/Matrix channel where we can talk about it? If not, you can always find me on #gnome-design.

**Comment by haecker-felix** [comment]
Very nice, i'm on #gnome-design now too.
