### ISSUE TITLE
previous and next keys won't work

### ISSUE THREAD

**Issue by sispus** [haecker-felix/gradio#280]
Hi,
gradio 7 is great. However, I could't make previous and next keys work. Play-pause works. I'm on manjaro xfce linux. I use "playerctl" for the function. It works with other players and gradio 6/master as expected, but not with gradio 7. 

There is an interesting thing. When I click a station, a thin frame emerges around the station icon. This frame blinks when I push play-pause key, as well as I push next/previous keys, but not other keys. It is like gradio "gets" the command but not "obeys" it :)  

## Expected Behavior

When I push the previous/next or play-pause keys in keyboard, gradio must change the station with previous/next one or play-pause the station
## Current Behavior

Gradio plays-pauses but not changes the station.
## Steps to Reproduce

1.Click on a station.
2. Push next or previous keys
3. Gradio won't change the station, but the thin frame around the station icon will blink.
4.

**Comment by haecker-felix** [comment]
Yes, i've removed this feature because it is not longer supported by Gradio itself. I merged the collections page with the library page. The new underlying codebase, doesn't support this anymore, without much work. Sorry.
