### ISSUE TITLE
Move Home and refresh button to the Headerbar

### ISSUE THREAD

**Issue by bil-elmoussaoui** [haecker-felix/gradio#29]
Can you please move the home and refresh button to the headerbar and either hide/show them or make the (un)sensitive?
The same for the search bar, if you can make it looks more like a gnome app that would be great! you can take a look at gnome books, or evince for an example :+1:

**Comment by haecker-felix** [comment]
No because I planned to add more items to the "Discover"-toolbar. In the header bar there is no enough space.
