### ISSUE TITLE
Add "Quit" to desktop file?

### ISSUE THREAD

**Issue by orschiro** [haecker-felix/Gradio#292]
Hey all, 

Proposing this as enhancement to more clearly close Gradio without having it run in background. 

I noticed from Skype that it has this useful "Quit" entry on the icon. 

Can we add a similar entry to the Gradio desktop file? :-)

Attaching some screenshots that hopefully explain what I mean.

Thank you!

![image](https://user-images.githubusercontent.com/170947/35912749-c6581aba-0bfd-11e8-9c2e-e2d7b39fae29.png)

![screenshot from 2018-02-06 15-04-15](https://user-images.githubusercontent.com/170947/35912758-cbf25fda-0bfd-11e8-9e0c-85831cbe0c7d.png)

**Comment by haecker-felix** [comment]
![gradio_exit_demo](https://user-images.githubusercontent.com/6001248/35928635-ec3cccc8-0c2d-11e8-84cd-56683c03e242.png)

There is already a "Quit" option in the appmenu, which completely closes Gradio ;)

**Comment by orschiro** [comment]
Hmm is this a custom extension? 

I don't have this on vanilla Fedora 27. :-(

![image](https://user-images.githubusercontent.com/170947/35928866-8604a560-0c2e-11e8-8f3d-fbd45fa8f805.png)

**Comment by haecker-felix** [comment]
Huh? No this should be default. However the menu in the headerbar. Just click on the Gradio icon, next to the back button (left).

**Comment by orschiro** [comment]
> Huh? No this should be default.

Hm, at least not on Fedora. :-(

> However, it's in the headerbar menu. Just click on the Gradio icon, next to the back button (left).

Yes, there it is but not very obvious to look there (at least for me). 

What's against adding it to the dash icon?

![image](https://user-images.githubusercontent.com/170947/35930433-2da466ae-0c32-11e8-8890-8fa4d1af00d1.png)

**Comment by haecker-felix** [comment]
I'm using Fedora as daily driver, and it works for me. I'll look after it. Can you post your Gradio terminal output? It contains some useful information for me, to fix this bug.

**Comment by orschiro** [comment]
> I'm using Fedora as daily driver, and it works for me.

Strange! Which version? And you don't use a custom extension?

> . Can you post your Gradio terminal output? It contains some useful information for me, to fix this bug.

Sure, thanks a bunch!

```
[orschiro@localhost ~]$ flatpak run de.haeckerfelix.gradio/x86_64/stable
** Message: gradio-app.vala:192: Gradio 7.1 
** Message: gradio-app.vala:200: Locale dir: /app/share/locale
** Message: gradio-app.vala:142: Registered search provider service.
** Message: gradio-app.vala:135: Desktop session is: gnome
** Message: gradio-library.vala:75: Open database...
** Message: gradio-library.vala:76: /home/orschiro/.var/app/de.haeckerfelix.gradio/data/gradio/gradio.db
** Message: gradio-library.vala:46: Successfully opened database! Reading database data...
** Message: gradio-main-window.vala:271: Changed page mode to "library"

** (gradio:2): WARNING **: gradio-utils.vala:98: Empty station data

** (gradio:2): CRITICAL **: gradio_station_model_add_item: assertion 'item != NULL' failed

** (gradio:2): WARNING **: gradio-utils.vala:98: Empty station data

** (gradio:2): CRITICAL **: gradio_station_model_add_item: assertion 'item != NULL' failed

** (gradio:2): WARNING **: gradio-utils.vala:98: Empty station data

** (gradio:2): CRITICAL **: gradio_station_model_add_item: assertion 'item != NULL' failed
```

**Comment by phw** [comment]
@orschiro Having the app menu visible is definitely the default on Fedora, and it's one of the core parts of the Gnome UI :) But it can be disabled in Gnome Tweaks, maybe you configured it there?

**Comment by phw** [comment]
About the issue: I can see how this feature could be useful for an app that is often running in the background

**Comment by orschiro** [comment]
> Having the app menu visible is definitely the default on Fedora, and it's one of the core parts of the Gnome UI :) But it can be disabled in Gnome Tweaks, maybe you configured it there?

Just asked some more Fedora users on the Telegram group and they told me that also for them it's not default. Weird....but yes it can be enabled in Tweaks > Top Bar > Application menu

> About the issue: I can see how this feature could be useful for an app that is often running in the background

Thaanks! :-)

**Comment by orschiro** [comment]
Never mind, you were right! I just ran `dconf reset -f /` and now I have back this app menu by default :)
