### ISSUE TITLE
Add Help Overlay

### ISSUE THREAD

**Issue by julianrichen** [haecker-felix/gradio#3]
It would be nice if we could have the shortcut window/help overlay, so the application follows the GNOME HIG:
https://wiki.gnome.org/Design/OS/HelpOverlay

I'm not to familiar with vala but this seems to describe the way to add accelerators:
https://esite.ch/2011/02/global-hotkeys-with-vala/

Example (GNOME Builder):
![](http://i.imgur.com/cJi5eUe.png)
![](http://i.imgur.com/HfcwVFh.png)

**Comment by haecker-felix** [comment]
This feature require GTK 3.20. Currently gradio uses GTK 3.14 because i want to support many distros. But it isn't very important (my opinion) because gradio actually hasn't any key shortcut. (*actually*)

**Comment by haecker-felix** [comment]
But some key shortcuts are comming :+1:
