### ISSUE TITLE
[Kali Linux/Debian SID] cmake fails for recents libraries and naming issues

### ISSUE THREAD

**Issue by kcdtv** [haecker-felix/gradio#30]
I tried to install from source in Kali Linux (a debian SID fork) and got four errors when i launched cmake
<code>Checking for modules glib-2.0;gtk+-3.0>=3.18;gstreamer-1.0;json-glib-1.0;gio-2.0;gee-0.8;libsoup-2.4
   No package 'gstreamer-1.0' found
   No package 'json-glib-1.0' found
   No package 'gee-0.8' found
   No package 'libsoup-2.4' found
</code>
If i check my "libsoup" I can see that i have it installed but with a kind of higher version and a different name
<code>ii  libsoup2.4-1:amd64                     2.54.1-1                             amd64        HTTP library implementation in C -- Shared library
</code>
What could I modify to compile properly? I am pretty sure that it will work with this library 
I just need to find the naming check to modify it to try, 
For the record that what i have installed for the other three fail dependencies
<code>kcdtv@ramonperez:~/gradio/build$ dpkg -l | grep json-glib-1.0
ii  libjson-glib-1.0-0:amd64               1.2.0-1                              amd64        GLib JSON manipulation library
ii  libjson-glib-1.0-common                1.2.0-1                              all          GLib JSON manipulation library (common files)
</code>
<code>kcdtv@ramonperez:~/gradio/build$ dpkg -l | grep gstreamer-1.0
ii  gir1.2-gstreamer-1.0                   1.8.2-1                              amd64        GObject introspection data for the GStreamer library
</code>
and for gee i am not sure, i will check it out later

edit-----------

I found the gee dependency, it is **gir1.2-gee-0.8** error was mine...
For the rest i still have this three failing while they are installed (it seems to me)
<code>--   No package 'gstreamer-1.0' found
--   No package 'json-glib-1.0' found
--   No package 'libsoup-2.4' found
</code>

**Comment by haecker-felix** [comment]
Which package system does kali use? If apt/deb you can simply install the deb package. Sorry i never worked with kali linux.

**Comment by kcdtv** [comment]
Don't be sorry 
To be fair Kali Linux is not a common distribution, it is a derivate from debian SID (unstable)  and it uses indeed *.deb packages. (it is like having debian SID with some special repositories for pentesting) 
<code>  uname -a
Linux ramonperez 4.6.0-kali1-amd64 #1 SMP Debian 4.6.3-1kali1 (2016-07-12) x86_64 GNU/Linux </code>
I did not try with the debian package 'cause I wanted to have the 4.10
I do it now and to tell you if that worked better than with the source...

.... **The version 4.0 in .deb package was installed successfully in KJali linux!**

  I don't know why I couldn't do it with sources... My knowledge in compiling with cmake is... none....
Thanks a lot for your work by the way, 
It is very stable and fast, very few resource are consumed and it does perfectly the job.
I am right now having a lot of fun listening  to music from the 50' on an Irish radio. 
It is a song to give advice to drivers: "Don't drink, keep your eyes on the road..." So funny! 
:smiley_cat: 
  I close the issue as the problem is solved, we can install the *.deb for Ubuntu in Debian SID and Kali Linux
If i have time to try more and find a workaround for installing the source i will post it here!  
  Thanks again!
