### ISSUE TITLE
Gradio on Raspberry

### ISSUE THREAD

**Issue by cm169** [haecker-felix/Gradio#303]
Hello

I installed Gradio from latest source (7.1) on Raspberry PI 3 B+ (OS Raspibian, release:  2018-03-13, kernel 4.9).
Everything worked, except no sound came from speakers when radio station is connected.
I checked sound functionality of the Pi with other software or with live streaming on web and it works flawlessly. I also checked Gradio with multiple radio stations with no success. No errors (beside few warrnings) on terminal output as well.
Any suggestion what can be wrong? 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by haecker-felix** [comment]
Sorry, no idea. I can't help you. 

I've tested Gradio on my RaspberryPi with the latest raspbian (fully updated), and everything works fine.
