### ISSUE TITLE
 g_object_set: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by ForumLiker** [haecker-felix/Gradio#309]
gradio 7.1 from master
4.15.15-1-ARCH
all dependencies are set
gradio
`
** Message: 22:08:11.228: gradio-app.vala:192: Gradio 7.1
** Message: 22:08:11.230: gradio-app.vala:200: Locale dir: /usr/local/share/locale
** Message: 22:08:11.333: gradio-app.vala:142: Registered search provider service.
** Message: 22:08:11.338: gradio-app.vala:135: Desktop session is:

** (gradio:10062): CRITICAL **: 22:08:11.338: string_contains: assertion 'self != NULL' failed

(gradio:10062): GLib-GObject-CRITICAL **: 22:08:11.338: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: 22:08:11.339: gradio-library.vala:75: Open database...
** Message: 22:08:11.339: gradio-library.vala:76: /home/user/.local/share/gradio/gradio.db
** Message: 22:08:11.339: gradio-library.vala:46: Successfully opened database! Reading database data...

** (gradio:10062): CRITICAL **: 22:08:11.350: string_contains: assertion 'self != NULL' failed
** Message: 22:08:11.448: gradio-main-window.vala:271: Changed page mode to "library"

(gradio:10062): GLib-GObject-CRITICAL **: 22:08:11.517: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Segmentation error (the memory stack is flushed to disk)
`

**Comment by haecker-felix** [comment]
which desktop?

**Comment by ForumLiker** [comment]
Cinnamon 3.6.7

**Comment by haecker-felix** [comment]
Enter "export" in a terminal, and look for the value of **DESKTOP_SESSION**

Or does it even exist?

**Comment by ForumLiker** [comment]
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x XDG_CURRENT_DESKTOP="X-Cinnamon"

**Comment by ForumLiker** [comment]
any ideas for solving my problem?

**Comment by haecker-felix** [comment]
Short: No. My laptop is broken. I can't fix anything right now.

Long: I believe you are missing the "DESKTOP_SESSION" env variable. You could set it manually. Maybe it helps.

**Comment by ForumLiker** [comment]
export DESKTOP_SESSION="cinnamon"

`$ gradio 
** Message: 17:26:13.616: gradio-app.vala:192: Gradio 7.1 
** Message: 17:26:13.619: gradio-app.vala:200: Locale dir: /usr/local/share/locale
** Message: 17:26:13.821: gradio-app.vala:142: Registered search provider service.
** Message: 17:26:13.827: gradio-app.vala:135: Desktop session is: cinnamon

(gradio:4624): GLib-GObject-CRITICAL **: 17:26:13.827: g_object_set: assertion 'G_IS_OBJECT (object)' failed
** Message: 17:26:13.852: gradio-library.vala:75: Open database...
** Message: 17:26:13.852: gradio-library.vala:76: /home/user/.local/share/gradio/gradio.db
** Message: 17:26:13.866: gradio-library.vala:46: Successfully opened database! Reading database data...
** Message: 17:26:14.059: gradio-main-window.vala:271: Changed page mode to "library"

(gradio:4624): GLib-GObject-CRITICAL **: 17:26:14.109: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Segmentation error (the memory stack is flushed to disk)
`

**Comment by ForumLiker** [comment]
After update:
gst-plugins-bad (1.14.0-2 -> 1.14.1-1)
gst-plugins-base (1.14.0-1 -> 1.14.1-1)
gst-plugins-good (1.14.0-1 -> 1.14.1-1)
gst-plugins-ugly (1.14.0-1 -> 1.14.1-1)
Gradio was started
 $ gradio
** Message: 09:34:53.365: gradio-app.vala:192: Gradio 7.1 
** Message: 09:34:53.367: gradio-app.vala:200: Locale dir: /usr/local/share/locale
** Message: 09:34:53.455: gradio-app.vala:142: Registered search provider service.
** Message: 09:34:53.465: gradio-app.vala:135: Desktop session is: cinnamon
** Message: 09:34:53.467: gradio-library.vala:75: Open database...
** Message: 09:34:53.467: gradio-library.vala:76: /home/user/.local/share/gradio/gradio.db
** Message: 09:34:53.467: gradio-library.vala:46: Successfully opened database! Reading database data...
** Message: 09:34:53.570: gradio-main-window.vala:271: Changed page mode to "library"
** Message: 09:34:54.580: gradio-audio-player.vala:83: Connecting to: http://ep256.hostingradio.ru:8052/europaplus256.mp3
