### ISSUE TITLE
Gradio.gnome.extension feature request

### ISSUE THREAD

**Issue by Aeron1** [haecker-felix/Gradio#311]
it would be nice if Gradio.gnome.extension wouldt show notifications in Gnome desktop like Gradio.app does.
It would also be nice if it would be possible to sort the radio stations and add stations without having to start Gradio.gnome.extension via Gnome.software first

**Comment by haecker-felix** [comment]
What do you mean? The GNOME shell extension "Gradio"?

**Comment by Aeron1** [comment]
yes, this one. Isn't it from you?


-------- Weitergeleitete Nachricht --------

Datum: Sun, 08 Apr 2018 02:27:15 -0700
Betreff: Re: [haecker-felix/Gradio] Gradio.gnome.extension feature
request (#311)
Kopie: Aeron1 <francko@a1.net>, Author <author@noreply.github.com>
An: haecker-felix/Gradio <Gradio@noreply.github.com>
Reply-to: haecker-felix/Gradio <reply+024373fa33824e46ea3aff4889649b0d5
80148b96b60e07c92cf0000000116e1a27392a169ce129d27fa@reply.github.com>
Von: Häcker Felix <notifications@github.com>
What do you mean? The GNOME shell extension "Gradio"?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/haecker-
felix/Gradio","title":"haecker-felix/Gradio","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/asset
s/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in GitHub","url":"https://gith
ub.com/haecker-
felix/Gradio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hae
cker-felix in #311: What do you mean? The GNOME shell extension
\"Gradio\"?"}],"action":{"name":"View Issue","url":"https://github.com/
haecker-felix/Gradio/issues/311#issuecomment-379535399"}}}

**Comment by haecker-felix** [comment]
No. It's something completely different. Just the same name.
