### ISSUE TITLE
 Failed to start flatpak-de.haeckerfelix.gradio-3460.scope.

### ISSUE THREAD

**Issue by dino99** [haecker-felix/Gradio#313]
Using Ubuntu Bionic, and get this logged:

ubuntu systemd[1271]: Failed to start flatpak-de.haeckerfelix.gradio-3460.scope.

but gradio seems working as expected; so no idea if i need to be scared. Just to let you know about.

**Comment by haecker-felix** [comment]
Seems to be a flaptak issue, not a Gradio issue itself.
