### ISSUE TITLE
Position format string

### ISSUE THREAD

**Issue by ovari** [haecker-felix/Gradio#316]
#: src/gradio-searchbar.vala:201
#, c-format
msgid "Sorting: %s / %s"

Suggestion:
Replace:
msgid "Sorting: %s / %s"
with:
msgid "Sorting: %1$s / %2$s"

and other places where needed.

https://docs.weblate.org/en/weblate-2.20/user/checks.html#c-format

**Comment by haecker-felix** [comment]
Thanks for tip, but not a real "issue", as this is working too :smiley: 

I am not changing that, as all translations would have to be updated.

**Comment by ovari** [comment]
It may help when translating into other languages. Have you looked at the other places too?
