### ISSUE TITLE
[Feature request] Folders to organize stations in the local library

### ISSUE THREAD

**Issue by actionless** [haecker-felix/Gradio#318]
Subj. I think lot of the users will find it nice to put favorite stations by genre or by home/office/camping music or so.

**Comment by haecker-felix** [comment]
Huh? That is already possible. Which version of Gradio are you using? Just right click a station in your library, and add it to a 'Collection'

**Comment by actionless** [comment]
sorry, didn't noticed that button in the corner

thanks a lot for your product and prompt response!

**Comment by actionless** [comment]
btw, mb move it from bottom right to bottom left, close to button for adding to library?
