### ISSUE TITLE
Create a package Flatpak

### ISSUE THREAD

**Issue by felipehw** [haecker-felix/gradio#32]
With a package Flatpak, the people using distributions without Gradio in their repo can enjoy this software :D

Obs: I dont know make flatpaks ... Just a ordinary user :/

**Comment by haecker-felix** [comment]
A flatpak is definitely comming!

**Comment by felipehw** [comment]
Thanks :+1:

**Comment by probonopd** [comment]
Please also consider an AppImage which would have the advantage of also working on Live and non-Fedora systems without the need for installing anything. See #75

**Comment by haecker-felix** [comment]
@probonopd I'm sure it will be possible to use flatpak out-the-box on other distributions soon.

@felipehw done :)

**Comment by probonopd** [comment]
@haecker-felix that won't help my CentSO 6 ;-/ and also it's not working on Live systems.
