### ISSUE TITLE
Some stations favicons address have changed and need to be modified

### ISSUE THREAD

**Issue by resoluti0n-coding** [haecker-felix/Gradio#323]
Some stations favicon address have changed and need to be modified.

Example: The Electro Swing Revolution Station

Broken current favicon address: http://www.electrosp-content/uploads/2017/06/ESR_Logo_140.png

New updated favicon address should be: http://www.electroswing-radio.com/wp-content/uploads/2017/06/ESR_Logo_140.png

**I tried to edit it myself but I get a "edit is disabled for now, because of vandalism" from the server.

**Comment by haecker-felix** [comment]
I'm not the maintainer of the database/server. I can't fix this. 

More information here:

https://github.com/segler-alex/radiobrowser-api/issues/39

**Comment by mailinglists35** [comment]
@haecker-felix can you put this in the FAQ? i'm sure i'm not the last one to get the error
