### ISSUE TITLE
little detail: use placeholders on startup

### ISSUE THREAD

**Issue by mjourdan** [haecker-felix/Gradio#326]
Here is a small suggestion to improve the UX.

## Expected Behavior

Gradio immediately displays the library.

## Current Behavior

During a short but still noticeable time, a message says the library is empty. This makes the user worry she has lost her collection.

## Steps to Reproduce

Cold start gradio.

## Detailed Description

On startup, the library should show as many placeholders as there are items in the library, and progressively replace them with actual content while loading.

**Comment by haecker-felix** [comment]
I'm currently completely rewriting Gradio in Rust with a new adaptive user interface (compatible to Librem5). This is more or less already fixed in the rust_port branch. The rust version is going to be the next version of Gradio (probably 8.0).

**Comment by mjourdan** [comment]
Thank you for the answer. Thanks much for keeping improving Gradio, I remember a time where the ui felt a bit crowded, but since 6.0 I think it turn to be very neat. Can't wait to see the new adaptive interface!
