### ISSUE TITLE
Arabic name dosent show correctly

### ISSUE THREAD

**Issue by sigmaSd** [haecker-felix/Gradio#327]
## Expected Behavior
Arabic station name should render correctly

## Current Behavior
If you add an arab station name , some words are replaced with symbols

## Detailed Description
Picture better then thousand word
[https://postimg.cc/image/6umoruahz/](https://postimg.cc/image/6umoruahz/)

**Comment by haecker-felix** [comment]
Small hint: You can post pictures directly on GitHub.

![grafik](https://user-images.githubusercontent.com/6001248/41500030-d5a90310-718a-11e8-9639-26c27791036a.png)

Seems to be a encoding issue in the webservice. I'll look after it.

**Comment by sigmaSd** [comment]
Thanks, my bad didn't check.

**Comment by sigmaSd** [comment]
Its fixed on the rust port , should I just close the issue?

**Comment by haecker-felix** [comment]
Oh, nice!
