### ISSUE TITLE
Can't add stations to library

### ISSUE THREAD

**Issue by joenoone** [haecker-felix/Gradio#344]
I imported the station DB from radio-browser.info and it removed all my library entries and I am unable to add anything now to my library. I can click on "add stations to library" and choose a station and click "add to library", but it continues to show "your library is empty". I am running Fedora 28.

**Comment by haecker-felix** [comment]
Why and how did you import the db from radio-browser.info?

**Comment by joenoone** [comment]
I downloaded from their page where it says : 
"A daily backup of the MariaDB tables is at www.radio-browser.info/backups/ and latest." 
(Latest = http://www.radio-browser.info/backups/latest.sql.gz). I unzipped it and from Gradio did Library->Import

**Comment by haecker-felix** [comment]
1. You cannot import the maria db tables. The file format is completely different. Gradio uses sqlite.

2. You don't need to import the stations. You already have them. Gradio is using Radio-Browser.info as data provider. All stations from the webpage are also available in Gradio.

3. To solve your issue: Just delete the broken gradio.db file. The path depends on your package type (flatpak/native). To find it out, you can start Gradio from your terminal. Now you should see a lot log messages. Somewhere you should see the library path.

**Comment by joenoone** [comment]
That fixed it, thanks.
