### ISSUE TITLE
[DESIGN SUGGESTION] Alternative collections interface

### ISSUE THREAD

**Issue by germanfr** [haecker-felix/Gradio#347]
I want to suggest an alternative design for the current implementation of colections. I don't use them because stations are too many clicks away and I don't feel comfortable. I suggest this, where stations are organized separated by sections instead of folders. Folders make sense when there are many (many) items to sort, but it is not the case. This way looks cleaner and it's more functional. Sations are visually organized and easy to access. And if you have many items you can always make covers smaller.
![gradio](https://user-images.githubusercontent.com/10391266/45239593-0de2f500-b2e6-11e8-8d8c-f8bdcd63f0bb.png)
Regarding the implementation, I think it is not hard to implement, and even I would say it simplifies things by removing the "folder view".

**Comment by haecker-felix** [comment]
Thanks for your Mockup :-)

I had the same idea, I'm currently working on it :+1:
