### ISSUE TITLE
Make gradio translatable

### ISSUE THREAD

**Issue by prescott66** [haecker-felix/gradio#35]
It would be nice to have gradio fully translatable, and to have all strings in POT template.

**Comment by raphaelh** [comment]
And it would be nice to add the projet to Weblate too :smile:

[Weblate ](https://weblate.org/)is a nice FOSS web-translation tool which can either be self-hosted, or can host FOSS projects for free

It comes with native support for GitHub and Gitlab hooks: https://docs.weblate.org/en/latest/admin/continuous.html

**Comment by haecker-felix** [comment]
@raphaelh gradio is now translatable on weblate.  Just check the readme. But please note, the Translation support is still work in progress.

**Comment by haecker-felix** [comment]
Gradio is now fully translatable. Weblate support is still -wip-. I have some problems with weblate, but already contacted the administrator team. I hope they can help me. 

In the meanwhile i accept translation pull requests here directly in github.
