### ISSUE TITLE
rpm install instructions for fedora

### ISSUE THREAD

**Issue by mailinglists35** [haecker-felix/Gradio#350]
the [wiki](https://github.com/haecker-felix/gradio/wiki/Install-Instructions) says it only supports flathub, but it should at least make a reference to an unsupported rpm distributed by [unitedrpms](https://unitedrpms.github.io/#repository)

it was much easier for me to install the rpm 

thanks

**Comment by nicoulaj** [comment]
There is also [copr repository](https://copr.fedorainfracloud.org/coprs/heikoada/gradio/)

**Comment by tim77** [comment]
Updated version with new multiple language support available on [Copr repos](https://copr.fedorainfracloud.org/coprs/atim/gradio/).

Installation Instructions:
`sudo dnf copr enable atim/gradio && sudo dnf install gradio -y`

**Comment by tim77** [comment]
https://github.com/haecker-felix/Gradio/issues/366

**Comment by haecker-felix** [comment]
Gradio is now available in the official fedora repository. See #366 for more details.
