### ISSUE TITLE
Gradio keeps playing even if app is closed

### ISSUE THREAD

**Issue by heis2201** [haecker-felix/Gradio#352]
## Expected Behavior
I close the Gradio window - the app should quit.

## Current Behavior
I close the Gradio windows - the station keeps on playing (I have the flatpak installed, in case that matters)

## Steps to Reproduce

1. Install Gradio from flathub
2. Start Gradio, select a station to stream
3. Close the window (by clicking on the X button)
4. Observe the audio continue to play (integration in Gnome shell notifications still active and reactive)

## Detailed Description

Terminate Gradio when closing its window - current behavior is as if the user would minimize the window. However, we don't need that functionality twice.

**Comment by haecker-felix** [comment]
Well, that's a feature, and not a bug :-).

Settings -> Disable Background playback.

**Comment by heis2201** [comment]
Well, that's confusing. How do I ever terminate the app entirely and freeing the memory then? Why is this feature not called upon click on the "minimize" button?
