### ISSUE TITLE
Missing copr build for Fedora 29

### ISSUE THREAD

**Issue by Zokormazo** [haecker-felix/Gradio#364]
Althrought f29 is listed on the copr, there is no any gradio package on it
## Expected Behavior

Available f29 build on copr.

## Current Behavior
heikoada-gradio repository fails to sincronice on Fedora 29. Looking at copr webpage, there is no f29 build for gradio

**Comment by haecker-felix** [comment]
I don't maintain the copr repo, so I won't update it. However there is a package available on UnitedRPMs for Fedora 29.

Or even easier: Just use the flatpak package :)
https://flathub.org/apps/details/de.haeckerfelix.gradio

**Comment by tim77** [comment]
https://github.com/haecker-felix/Gradio/issues/350#issuecomment-460076392

**Comment by tim77** [comment]
https://github.com/haecker-felix/Gradio/issues/366
