### ISSUE TITLE
Gradio in official Fedora repos now

### ISSUE THREAD

**Issue by tim77** [haecker-felix/Gradio#366]
Hi. Gradio in official [Fedora repositories](https://bodhi.fedoraproject.org/updates/FEDORA-2019-f8e61ef878) now. 🎉 Just FYI.

How to install:
`sudo dnf install gradio`

Felix, thank you for your awesome app. Using it every day. 🙂

**Comment by haecker-felix** [comment]
Fantastic news! Thanks for the information! I hope that [Shortwave](https://gitlab.gnome.org/World/Shortwave) will also be packed as soon as it is ready :smile:
