### ISSUE TITLE
Feature request : add an option to "Resume playback on startup"

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#39]
What do you think about to have an option to "resume playback on startup" then latest listened  radio station will be played automatically next time you open gradio?

Thanks
Andrea

**Comment by mohamedsakhri** [comment]
Additionally to the usability of this feature it would make more sense for the "play/stop" entry in the tray icon. After starting the app this entry is active but does nothing. Either this feature should be implemented or the entry should be inactive until a station is clicked.

**Comment by haecker-felix** [comment]
@mohamedsakhri uhm what do you mean with "play/stop" entry?

**Comment by mohamedsakhri** [comment]
@haecker-felix When you right click on the tray icon there was two items: "play/stop" and "quit". You said you disabled that temporarily in another comment.

BTW: After the latest commits from yesterday Gradio crashes whenever I click on a station. Error: Segmentation fault!

**Comment by haecker-felix** [comment]
Yeah chill. I will add it soon. ^^

Can you open a new bug with the output?
