### ISSUE TITLE
Uniform font name and style of gui

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#4]
Hi,  i don't know if it is an intended behaviour but the gui use different font or style: may 

e.g.:

1) Radio font name uses always a sort of open sans font while imo shoud use the system font
2) http link of the radio in the player toolbar uses italic style while the normal style is  everywhere

- gradio compiled from latest commit https://github.com/haecker-felix/gradio/commit/a13fe0452799f4aba5ffb442808365c929a75b21
- Archlinux 
- Gnome 3.20

Nice project :)

**Comment by haecker-felix** [comment]
I'm not sure what you're meaning. But I changed the font of the result list to the system font. (v2.01).

**Comment by dasnoopy** [comment]
tnks for the quick fix..  
I noticed that same "issue" also for  the radio station name in the playerToolbar: this time a screenshot should help with my poor english :)

![font](https://cloud.githubusercontent.com/assets/296922/15635016/a8b4f634-25d3-11e6-983e-af6148c38f6e.png)

Regards

**Comment by haecker-felix** [comment]
Is going to be fixed in the next version ;).
