### ISSUE TITLE
valac problem

### ISSUE THREAD

**Issue by imesg** [haecker-felix/gradio#44]
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
...
Could NOT find Vala (missing: VALA_EXECUTABLE)
...

Fix for me:
cmake -DVALA_EXECUTABLE:NAMES=valac-0.32 -DCMAKE_INSTALL_PREFIX=/usr ..

Have three version of vala installed on gentoo system. None of them are default which as I think of it is a problem of gentoo and not gradio. Maybe this helps someone else to install it.

Have requested that gradio be added to repository for gentoo.

Thanks for gradio.

**Comment by kajzersoze** [comment]
@imesg, I've made 9999 ebuild, I'm not particularly interested in version ebuild but I guess it wouldn't be a problem to make that one as well. If you're interested let me know and I will upload it.
