### ISSUE TITLE
Play/Stop with space bare isn't working unless the toolbar player is clicked

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#46]
After starting a station you can't stop/resume it using the space bar. You have to stop the station from the toolbar player first (Which calls the handler `PlayStopButton_clicked`). After that you can stop/resume using the space bar. 
Changing the station requires repeating the same steps again.

**Comment by haecker-felix** [comment]
In other words: Spacebar to toggle play/stop.

Is this what do you mean?

**Comment by mohamedsakhri** [comment]
Yes. But without having to stop the station from the toolbar player first.

**Comment by haecker-felix** [comment]
CTRL + space
