### ISSUE TITLE
Saving/loading window dimensions and position broken

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#51]
In latest git master saving or loading the window dimensions and position is broken.

**Comment by kajzersoze** [comment]
That's weird, it wasn't working for me before but now it is.
What do you mean by broken ?
It's not saving or loading at all , or it does but it's wrong ?
Was it working before ?

**Comment by HeikoAdams** [comment]
That means if I close gradio maximized the window isn't maximized on next start. And if I close gradio with a normal window placed centered on screen the window isn't on that position on next startup of gradio

**Comment by kajzersoze** [comment]
Hmm, just tried that several times with other various combinations and it works.

Well, I don't know, might be the distro or something, I guess you will have to wait for author to come back and see what's going on.

**Comment by dasnoopy** [comment]
Maybe could help:  I noticed that (at least for me) store of window dimension and it position  on quit **doesn't work** as expected if I **disable "Close to tray"** option; 

If I leave **enabled "Close to tray"** option, dimension and position are saved on quit and loaded on next start  successfully.

Gradio latest commit 530ddded1b6bb1465e8689d9341722b716ec60f6 (139) on Archlinux 64bit and gnome 3.20.2

**Comment by kajzersoze** [comment]
That helps, indeed it doesn't work in that case, it's interesting that it does work with "Close to tray" disabled if you choose "Quit" from the app menu or "Quit" from systray, but if you close the window by clicking X on window then it doesn't.
Funny, anyway I'll try to see what's going on with that.

**Comment by haecker-felix** [comment]
Should be fixed. Thanks @kajzersoze!
