### ISSUE TITLE
Add an option to disable tray icon and notifications 

### ISSUE THREAD

**Issue by HeikoAdams** [haecker-felix/gradio#52]
Latest git master has a tray icon and notifications which can't be disabled. It would be nice to have an option to turn them on or off because for me at least the notifications are boring because the appear very often.

**Comment by haecker-felix** [comment]
Will be available as opt-in feature soon. Haven't time yet to improve this behaviour. Still in Greek holiday :)

**Comment by kajzersoze** [comment]
Close to tray was already there as an option, remember that you have to compile glib schemas.

**Comment by HeikoAdams** [comment]
Yes, but that does neither disable the tray nor the notifications

**Comment by kajzersoze** [comment]
Notifications will be available when @haecker-felix merge latest commit.

Option for Close to tray isn't to disable tray, but to close the app to tray or not.

**Comment by haecker-felix** [comment]
Merged. Thanks @kajzersoze

**Comment by mohamedsakhri** [comment]
After the latest commits the tray icon doesn't appear. The App keeps running when closed but the tray icon doesn't appear. I'm using XFCE as DE.

**Comment by haecker-felix** [comment]
Mhm what do you mean with 'commitS'. Can you be more specific? Thanks.

**Comment by mohamedsakhri** [comment]
I'm not sure after which commit this issue appeared because lately I had problems building the app. But it is definitely after starting 5.0 Beta.
