### ISSUE TITLE
+/- button in play bar

### ISSUE THREAD

**Issue by simonbcn** [haecker-felix/gradio#55]
It would be useful to add or remove a radio station (_to/from the library_) from the play bar:
![captura de pantalla de 2016-08-19 18-52-36](https://cloud.githubusercontent.com/assets/428231/17817354/5ef2cdea-663e-11e6-8951-c0f3fad56aff.png)

**Comment by haecker-felix** [comment]
I'm planning to integrate the action popover into the player bar (red). Currently I'm not sure how to do it without adding to much items to the bottom bar.

**Comment by mohamedsakhri** [comment]
Is this issue really closed? I pulled the last commits, compiled and reinstalled the app but I don't see any changes in the player bar.. 

![gradio_player_bar](https://cloud.githubusercontent.com/assets/2544216/18028782/2cf86cec-6c87-11e6-8e29-bb48141996fd.png)

**Comment by haecker-felix** [comment]
Thats definitely a old version. Make sure you don't use a cached version or start the wrong binary.

**Comment by haecker-felix** [comment]
![gradio_4_1](https://cloud.githubusercontent.com/assets/6001248/18032805/706b64c6-6d12-11e6-9be1-b85ce330ca9b.png)

See here

**Comment by mohamedsakhri** [comment]
@haecker-felix  Thanks, you are right. I managed to get the latest version.

I've got an error after running `make`:
```
/gradio/src/Data/Codec.vala:18.5-18.26: error: The name `set_desktop_id' does not exist in the context of `Gst.PbUtils.InstallPluginsContext'
				context.set_desktop_id("de.haeckerfelix.gradio.desktop");
				^^^^^^^^^^^^^^^^^^^^^^

```
I didn't open a new issue because I'm not sure if it's a bug or just because of my libraries.

I deleted 	`context.set_desktop_id("de.haeckerfelix.gradio.desktop");` from `Codec.vala` to get rid of the error and continue the installation.
