### ISSUE TITLE
full screen does not fit screen

### ISSUE THREAD

**Issue by MAlfare** [haecker-felix/gradio#58]
see attached picture.
screen is 1280x1024
linux mint cinnamon 18.0

sorry, the screen shot does not show the problem (missing parts of screen on all four sides).
As soon as I open the screen shot utility, screen fits.
So I cut the screen shot to what I can see in full screen mode.
![screen shot](https://cloud.githubusercontent.com/assets/4406655/17894578/1f6e5ad6-694a-11e6-8a56-21ad155f2542.jpg)

**Comment by haecker-felix** [comment]
This happens only on cinnamon. So i'm Not Sure if its gradio fault or gtk/cinnamon. On unity / KDE / gnome doesnt happen this. I will look after this but i cant guarentee anything.

**Comment by haecker-felix** [comment]
I've installed linux mint in a vm with the latest updates. Cannot reproduce.
