### ISSUE TITLE
Some icons are not suitable. Using custom icon set would be better?

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#62]
I think some icons in the icon  set used now aren't suitable to the items they are representing (See Screenshoot).
Wouldn't be better to use a custom icon set or a free icon font set like [fontawesome](http://fontawesome.io)  or [icomoon](https://icomoon.io)?

![gradio_icons](https://cloud.githubusercontent.com/assets/2544216/18026568/c4f03246-6c4b-11e6-9484-51e772379518.png)

**Comment by haecker-felix** [comment]
Since you opened this bug, much have changed. Which icon is not suitable now?

**Comment by mohamedsakhri** [comment]
Hard to tell, because the icons depend on the icon theme the system use. In some themes the icons are suitable( language, countries...), in others they are not.

**Comment by haecker-felix** [comment]
The problem is I use the stock gnome icon theme and all icons are suitable.  Now I don't know which icon I should change

**Comment by mohamedsakhri** [comment]
I think it is ok the way it is right now. If you want to be sure the app will use one specific stock you should deliver it with the app. But this wouldn't be a good practice.

**Comment by haecker-felix** [comment]
Font Awesome: No svg, only fonts...
IcoMoon: No correct icons for gradio.

Its very hard to find a icon, which fits to the gnome icon theme, and is free to use. 

I could create the icons myself, but i have no idea to use inkscape. I have two left hands in graphic editing / creation 😟

**Comment by mohamedsakhri** [comment]
You may would like to take a look at [Font-Awesome-SVG-PNG
](https://github.com/encharm/Font-Awesome-SVG-PNG)
