### ISSUE TITLE
Feature request: History of the recent played stations

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#63]
History of the recent played stations.  Players, like spotify, have this feature. Some new settings, like number of stations, order.. could be supported as well.

The feature could be implemented like in the screenshot :)

![gradio_history](https://cloud.githubusercontent.com/assets/2544216/18027090/05acf3e2-6c5a-11e6-85b4-2af64c3f8853.png)

**Comment by haecker-felix** [comment]
Please open one bug report for each feature request.

> History of the recent played stations  

-> Recently Clicked?

> number of stations

-> Already done. Next github push :)


> order

-> sort by what?

**Comment by mohamedsakhri** [comment]
Sorry but all the settings mentioned here are related to the requested feature. Here what I mean:

Feature: History of recent played stations
Settings to manage the history:
- number of stations to be displayed in the history list
- how to order the history list, by name or recent played first

**Comment by haecker-felix** [comment]
But there is alreade the feature "recently clicked" which is a history of clicked stations. Or not?

(except "how to order")

**Comment by mohamedsakhri** [comment]
No, the "recently clicked" feature shows the recently clicked stations from all users over the world. The history list would show my recent clicked stations.

**Comment by haecker-felix** [comment]
aaah now I understand it. 

But I think this feature is not really useful for a internet radio application (But for a music application!)

I set a note on my personal todo list, but don't except to much.

**Comment by mohamedsakhri** [comment]
Well, as a software developer I know that 90% of the features in an application aren't used by the most users..

Spotify has radios and a history feature as well :)

**Comment by haecker-felix** [comment]
That is a good fact. As i said: I've noted it. Currently there are more important feature than a history ;)

**Comment by mohamedsakhri** [comment]
Thanks. Maybe it would be better to let the issue open so that you can keep an eye on it when you got time :)
