### ISSUE TITLE
Notifications should be transient

### ISSUE THREAD

**Issue by simonbcn** [haecker-felix/gradio#65]
I think the notifications should be transient (https://wiki.gnome.org/Design/OS/Notifications#Transient), it isn't necessary that they remain in notification list:
![menu_001](https://cloud.githubusercontent.com/assets/428231/18028128/621e4ace-6c76-11e6-92d1-4b841d4147d4.png)

Otherwise notifications are accumulated in notification list.

**Comment by haecker-felix** [comment]
Thanks for the hint. Was easy to implent.

**Comment by simonbcn** [comment]
It still remains the notification in notification list:
![menu_001](https://cloud.githubusercontent.com/assets/428231/18028379/bbe717b4-6c7d-11e6-8606-251807cca868.png)

It should only show them.

**Comment by simonbcn** [comment]
I have updated today and it works well. It remains a few seconds in notification list then it disappears.
