### ISSUE TITLE
Adding station to library

### ISSUE THREAD

**Issue by kajzersoze** [haecker-felix/gradio#66]
How do you add station to library in this new layout ?
I can't figure it out.
Used to be by left clicking on a station and then pressing + , now on left click it just starts playing.
Right click does nothing.

**Comment by kajzersoze** [comment]
Ah I got it never mind.
So confusing now :)

**Comment by kajzersoze** [comment]
You should really add tooltips to buttons :P

**Comment by haecker-felix** [comment]
Jup. That is something with a high priority. 

Ideas how I can improve the new layout? (Or making it less confusing).

**Comment by kajzersoze** [comment]
Well I don't know, you seem to have a vision how that's supposed to look, I personally liked the previous layout but that's just me.

Anyway, at least add tooltips for each button , here... I added one for AddRemoveButton , you can apply the same for all the buttons (you just add one line for each button and change tooltip text, it's easy) , that would make it less confusing :

```
--- a/data/ui/player-toolbar.ui	2016-08-30 03:35:38.030069000 +0200
+++ b/data/ui/player-toolbar.ui	2016-08-30 03:38:33.440743607 +0200
@@ -357,6 +357,7 @@
     <child>
       <object class="GtkButton" id="AddRemoveButton">
         <property name="visible">True</property>
+        <property name="tooltip_text" translatable="yes" comments="Tooltip for AddRemoveButton">Add / Remove current playing station</property>
         <property name="can_focus">True</property>
         <property name="receives_default">True</property>
         <property name="relief">none</property>
```
