### ISSUE TITLE
Discussion: behaviour when the internet connection is lost

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#70]
**User case:** 
1. user starts a station
2. while the station is played the internet connection is lost
3. internet connection is back

**Behaviour now:**
An error message is displayed when the connection is lost and the station stops. After the connection is back you should click to start the station again.

**Optimal behaviour**
When the connection is lost the application should keep trying to connect. After the connection is back the station should resume playing without any action from the user.

This behaviour is adopted in most recent media/audio players. e.g Clementine adopts it while playing radio stations.

**Comment by haecker-felix** [comment]
Yup. I agree but it is currently hard to implent. Don't except this feature in 4.1.

**Comment by i30817** [comment]
I also want this so i'm commenting to get notified. At least as a option, i'd like a way to 'keep trying' even if silence happens.

**Comment by haecker-felix** [comment]
The optimal behaviour is now implemented :-)

**Comment by haecker-felix** [comment]
Code is already on master.
