### ISSUE TITLE
Do not hardcode height/width of GridListButton on headerbar (Gtk-3.18)

### ISSUE THREAD

**Issue by khurshid-alam** [haecker-felix/gradio#74]
It seems gradio set height/width to 40 which doesn't play well with some theme. And GridListButton looks ugly on headerbar 

![gradio](http://i.imgur.com/822ajLk.png)
![gradio-inspector](http://i.imgur.com/xd9PAlC.png)

**Comment by haecker-felix** [comment]
This is an old version of gradio. Already fixed in newer versions.

**Comment by haecker-felix** [comment]
This is an old version of gradio. Already fixed in newer versions.

**Comment by khurshid-alam** [comment]
@haecker-felix Can you update the PPA with the newer version. Thanks.

**Comment by haecker-felix** [comment]
Uhm which ppa?

**Comment by khurshid-alam** [comment]
@haecker-felix This one: https://launchpad.net/~haecker-felix/+archive/ubuntu/gradio-daily

**Comment by haecker-felix** [comment]
It contains the latest version.

**Comment by khurshid-alam** [comment]
@haecker-felix The latest version in the ppa is 4.x. Can we have 5.x in the PPA?

**Comment by haecker-felix** [comment]
5.x is currently in development
