### ISSUE TITLE
Provide a package for trusty in the ppa

### ISSUE THREAD

**Issue by probonopd** [haecker-felix/gradio#75]
Please provide a package for trusty or earlier in the ppa. It would allow to generate an [AppImage](http://appimage.org/) from it easily, which would make it possible for users of almost all distributions to try out gradio without having to install it.

Here is an example for how easy it is to generate an AppImage from a trusty ppa:
https://github.com/probonopd/AppImages/blob/master/recipes/leafpad/Recipe

**Comment by haecker-felix** [comment]
AppImage? Maybe if I have the time.

Trusty support? Unfortunately not possible. Gradio needs gtk 3.14 or higher. I'm sorry.
