### ISSUE TITLE
Can't start searching by pressing Enter

### ISSUE THREAD

**Issue by gorrila** [haecker-felix/gradio#76]
In the Discover-Tab I can't start searching by pressing Enter. I have to manually press the search button

To reproduce:
- Go to the Discover-Tab
- Enter something in the search field
- Press enter to start the search (nothing happens)

**Comment by mohamedsakhri** [comment]
Are you sure you have the latest build? This issue was known and fixed. See here: https://github.com/haecker-felix/gradio/issues/1

**Comment by gorrila** [comment]
You're right, I installed via the PPA
