### ISSUE TITLE
wrong user agent on half of the requests

### ISSUE THREAD

**Issue by segler-alex** [haecker-felix/gradio#8]
gradio 2.01 does send 2 requests for each search. this is not a problem, but the first one always has the wrong user agent. Example:
1.2.3.4 - - [29/May/2016:20:14:06 +0200] "GET /webservice/json/stations/byid/64094 HTTP/1.1" 200 829 "-" "gvfs/1.28.1"
1.2.3.4 - - [29/May/2016:20:14:06 +0200] "GET /webservice/json/stations/byid/64094 HTTP/1.1" 200 829 "-" "gradio/2.01"

or for example:

1.2.3.4 - - [29/May/2016:20:16:33 +0200] "GET /webservice/json/stations/byname/jazz HTTP/1.1" 200 39090 "-" "gvfs/1.28.1"
1.2.3.4 - - [29/May/2016:20:16:34 +0200] "GET /webservice/json/stations/byname/jazz HTTP/1.1" 200 39090 "-" "gradio/2.01"

**Comment by haecker-felix** [comment]
does this happened on previous versions (like 1.04)?

**Comment by segler-alex** [comment]
i looked at the logs and i don't see double logs in version 1.04
but 1.04 did a /webservice/json/stats with the wrong user agent on the start of the app

1.2.3.4 - - [29/May/2016:09:04:14 +0200] "GET /webservice/json/stats HTTP/1.1" 200 480 "-" "gvfs/1.28.2"

**Comment by haecker-felix** [comment]
_Should_ be fixed with the 2.2 release.
