### ISSUE TITLE
Can't star stations in "Discover" tab

### ISSUE THREAD

**Issue by crobe87** [haecker-felix/gradio#83]
I should be able to star a station directly from the Discovery tab.

**How it should be:** I search for a station's name, I see it, I click the star, done. 

**Now it fails:** instead of adding it to the library, it just plays it.
Then I can click the star on the bottom while it's playing to add it.

**TL;DR** The stars in the discovery tab, next to stations names aren't working.

**Comment by haecker-felix** [comment]
You're right ;)

I working on a right-click menu.

**Comment by haecker-felix** [comment]
Initial work for the new right click menu is done. Now a have to add the library button. See latest commit :smile:

**Comment by haecker-felix** [comment]
Right click menu is now fully implemented for list/grid view.
