### ISSUE TITLE
Not playing through USB sound card. My fault?

### ISSUE THREAD

**Issue by crobe87** [haecker-felix/gradio#84]
Ubuntu 16.04
Gradio 5.x built from source, second-last commit.
It only plays from internal soundcard, it doesn't play through the USB soundcard I have.
The official ppa release (4.0.1+r109-0~ubuntu16.04.1) instead works fine: as soon as I connect the usb card it switches the sound to the external sound card.

Other apps works fine. e.g VLC

Something wrong compiling or bug?

**Comment by haecker-felix** [comment]
Could you provide the terminal output? thanks.

**Comment by crobe87** [comment]
Latest build from git. Usb card already plugged in before starting gradio.

- gradio output:

> **  Message: main.vala:6: Starting Gradio version 5.0.0b2!
> ** Message: Library.vala:107: Reading library data from: /home/roberto/.local/share/gradio/library.gradio
> ** Message: Library.vala:132: Successfully imported library
> ** Message: MPRIS.vala:34: Successfully initialized MPRIS session.
> ** Message: MainWindow.vala:76: Desktop session is: i3
> ** Message: CategoryItemProvider.vala:36: Fetching category items...
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: Util.vala:96: Loaded CSS from: /usr/local/share/gradio/gradio.css
> ** Message: CategoryItemProvider.vala:127: Successfully loaded category items!
> ** Message: DiscoverSidebar.vala:127: Loading category items...
> ** Message: RadioStation.vala:86: Playable url: http://sc-blues.1.fm:8030/

> ** (gradio:8288): WARNING **: MPRIS.vala:167: MPRIS metadata is null

> ** (gradio:8288): WARNING **: MPRIS.vala:167: MPRIS metadata is null



- pastebin  ./autogen.sh
http://pastebin.com/aL3LVi9V

- pastebin  make
http://pastebin.com/Wnd44D4Y

- pastebin  make install
http://pastebin.com/KVrdJ6Q9


NOTE: I can reconfirm, just tried another time, that the gradio 4.0.1 from ubuntu ppa works fine. As soon I start and the usb card is plugged in, it plays on the usb sound card without any problem/input needed.

**Comment by haecker-felix** [comment]
> ** Message: Library.vala:107: Reading library data from: /home/roberto/.local/share/gradio/library.gradio
> ** Message: Library.vala:132: Successfully imported library
> ** Message: MPRIS.vala:34: Successfully initialized MPRIS session.
> ** Message: MainWindow.vala:76: Desktop session is: i3
> ** Message: CategoryItemProvider.vala:36: Fetching category items...
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: StationProvider.vala:82: Requested results from 0 to 20
> ** Message: Util.vala:96: Loaded CSS from: /usr/local/share/gradio/gradio.css
> ** Message: CategoryItemProvider.vala:127: Successfully loaded category items!
> ** Message: DiscoverSidebar.vala:127: Loading category items...
> ** Message: RadioStation.vala:86: Playable url: http://sc-blues.1.fm:8030/

> ** (gradio:8288): WARNING **: MPRIS.vala:167: MPRIS metadata is null

> ** (gradio:8288): WARNING **: MPRIS.vala:167: MPRIS metadata is null

There is nothing wrong with this output.  I haven't changed anything from 4.0.1 to 5.0.0b2 to the audio backend. 

Cannot be a bug in gradio itself. I'm sorry. 
Make sure to use the correct audio output in the system settings. 
This is a very unusual bug. Please wait until i release the final 5.0.0 in the PPA.
