### ISSUE TITLE
No Valid Frames decoded before End of Stream

### ISSUE THREAD

**Issue by Null-Senpai** [haecker-felix/gradio#85]
Every now and then I get the error message "No Valid Frames decoded before End of Stream" and the Radio stops.
I am using Gradio version 4.0.1 on Antergos (Kernel 4.4.23-1-lts).
Happy to provide any other details if needed.

**Comment by haecker-felix** [comment]
I'm sorry, but this is gstreamer related. Cannot fix this. 

This message is known. Just google it. There are several ways to fix it.
