### ISSUE TITLE
it is missing a plugin ...

### ISSUE THREAD

**Issue by GuGumo** [haecker-felix/gradio#86]
really i don t unterstand and don t find ...
this is writting
il manque un greffon dans l installation de Gstreamer
please help
and i can t install it from the source code
mix@MiX:~/Téléchargements/gradio-master$ sudo ./autogen.sh
./autogen.sh: 1: ./autogen.sh: autoconf: not found
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh\' command line.

**Comment by GuGumo** [comment]
mix@MiX:~/Téléchargements/gradio-master$ ./autogen.sh
./autogen.sh: 1: ./autogen.sh: autoconf: not found
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish t
o pass any to it, please specify them on the
*** `./autogen.sh\' command line.

./autogen.sh: 25: ./autogen.sh: aclocal: not found

**Comment by GuGumo** [comment]
mix@MiX:/home$ git clone https://github.com/haecker-felix/gradio.git
fatal: impossible de créer le répertoire de la copie de travail 'gradio': Permission non accordée

**Comment by GuGumo** [comment]
mix@MiX:/home$ cd /home/mix
mix@MiX:~$ git clone https://github.com/haecker-felix/gradio.git
Clonage dans 'gradio'...
remote: Counting objects: 2215, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 2215 (delta 57), reused 0 (delta 0), pack-reused 2106
Réception d'objets: 100% (2215/2215), 799.16 KiB | 406.00 KiB/s, fait.
Résolution des deltas: 100% (1592/1592), fait.
Vérification de la connectivité... fait.
mix@MiX:~$ cd gradio
mix@MiX:~/gradio$ ./autogen.sh
./autogen.sh: 1: ./autogen.sh: autoconf: not found
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh\' command line.

./autogen.sh: 25: ./autogen.sh: aclocal: not found

**Comment by haecker-felix** [comment]
Aclocal is missing. Install the correct package for your distribution.

**Comment by haecker-felix** [comment]
Aclocal is missing. Install the correct package for your distribution.

**Comment by GuGumo** [comment]
thank's
was a problem in the kernel i change it and run now very weel
