### ISSUE TITLE
Flatpak installation failure

### ISSUE THREAD

**Issue by AlbertHilb** [haecker-felix/gradio#89]
I'm on Ubuntu 16.04.
Running the command
```
flatpak install haeckerfelix-repo de.haeckerfelix.gradio
```
I get an error
```
Invalid name de.haecker-felix.gradio: Only last name segment can contain -
```

**Comment by haecker-felix** [comment]
I'm sorry, in the documentation was a typo. 

Instead of
`flatpak install haeckerfelix-repo de.haecker-felix.gradio`

**it should be**
`flatpak install haeckerfelix-repo de.haeckerfelix.gradio`

**Comment by AlbertHilb** [comment]
Thanks a lot! :-)
