### ISSUE TITLE
Missing tray icon

### ISSUE THREAD

**Issue by AlbertHilb** [haecker-felix/gradio#90]
I'm on KDE Neon 5.8, essentially Ubuntu 16.04 with KDE Plasma 5.8.
If "Close to tray" option is selected, on closing the app, the window disappears but no icon is added to the tray.

**Comment by haecker-felix** [comment]
Should work now with the latest commit.

**Comment by mohamedsakhri** [comment]
It works. But the feature to play/stop on right click isn't available.  It was available after this commit a4a9a92b7b064bfe07cd23a345512f5a63bc065b

**Comment by haecker-felix** [comment]
Yeah I know. I've removed it temporary.
