### ISSUE TITLE
Implement MPRIS previous/next for Library radios

### ISSUE THREAD

**Issue by crobe87** [haecker-felix/gradio#91]
So that one could shuffle through the library radios (starred ones), playing the next or the previous radio in the list quickly without opening gradio.

e.g. this would allow to use the previous/next buttons in the volume menu in some desktop environments (ubuntu/unity) and/or XF86 media keys previous/next if one wants.

**Comment by haecker-felix** [comment]
Yes. I have planned this. ^^

**Comment by haecker-felix** [comment]
Mhm it's hard to add this currently. The library is stored as a glib hashmap. Getting the "next" item is a bit hard with the hashmap. Maybe you find a better solution. Yes I could switch to a Gee List, but than i must change everything in the backend.
