### ISSUE TITLE
Process still running after closing the GUI

### ISSUE THREAD

**Issue by crobe87** [haecker-felix/gradio#92]
I close the GUI but I can see in top that gradio process is still running.
Also the audio is running!!!

Didn't notice before because I had headphones connected under the desk and didn't hear sound was continuing after closing it :(

Also I see the "Minimize to tray icon" is disabled in settings. Maybe is trying to minimize on close by default?

Appeared just after fixed #82, I think commit b992ddc80dc880d63cdadedbfb474b5a4610faf3 caused this.

Both i3 and Unity. Ubuntu 16.04

**Comment by haecker-felix** [comment]
Fixed. However it wasn't a real bug. Just the incomplete "background playback"-feature. Now you can re-access the old process over the mpris tray, or the desktop file.

However you can disable the whole feature in the settings now.
