### ISSUE TITLE
autogen.sh - errors out when executed on Ubuntu 14.04

### ISSUE THREAD

**Issue by wgregori** [haecker-felix/gradio#97]
I'm trying to install Gradio on Ubuntu 14.04.... here are the results.

wayne@wayneOfficeDesktop:~/Downloads/gradio$ ./autogen.sh
./autogen.sh: 1: ./autogen.sh: autoconf: not found
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh\' command line.

./autogen.sh: 25: ./autogen.sh: aclocal: not found

Thanks for any help you might provide.

Wayne

**Comment by mohamedsakhri** [comment]
Make sure the dependencies listed in the `Readme.md` are installed in your Ubuntu. In this case try this:
`sudo apt-get install autotools-dev automake`

**Comment by haecker-felix** [comment]
Thanks @mohamedsakhri. Reopen if the error still persist.
