### ISSUE TITLE
Gradio GStreamer

### ISSUE THREAD

**Issue by csola48** [haecker-felix/gradio#98]
Error: "GStreamer a complement is missing from setup."
![kepmentes_005](https://cloud.githubusercontent.com/assets/893186/19836151/31a85b4c-9e98-11e6-9ab7-ac700c7bbe04.png)

**Comment by haecker-felix** [comment]
My computer is broken. Fix may take much longer. I'm sorry.

**Comment by csola48** [comment]
2016-11-02 19:29 keltezéssel, Häcker
      Felix írta:
    
    
      My computer is broken. Fix may take much longer. I'm sorry.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haecker-felix/gradio","title":"haecker-felix/gradio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haecker-felix/gradio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haecker-felix in #98: My computer is broken. Fix may take much longer. I'm sorry."}],"action":{"name":"View Issue","url":"https://github.com/haecker-felix/gradio/issues/98#issuecomment-257956874"}}}
    
    Thx your answer :(
    
    csola48

**Comment by haecker-felix** [comment]
I'm sorry i but i cannot reproduce. This station is working for me fine. Make sure your gstreamer setup is correct.

**Comment by csola48** [comment]
The system is fresh, new setup (Ubuntu 16.04.1 / 32bit).
Which component is needed of Gstreamer ?
The libgstreamer is installed...
GRadio invariably works wrongly ... :(

Thank you
![kepmentes_010](https://cloud.githubusercontent.com/assets/893186/20461807/9f778eaa-af09-11e6-9926-c8ff920571e1.png)
![kepmentes_012](https://cloud.githubusercontent.com/assets/893186/20461808/a3572c74-af09-11e6-9434-5c8dfe73704f.png)
csola48

**Comment by csola48** [comment]
2016-11-19 16:12 keltezéssel, Häcker
      Felix írta:
    
    
      I'm sorry i but i cannot reproduce. This station is working for
        me fine. Make sure your gstreamer setup is correct. 
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haecker-felix/gradio","title":"haecker-felix/gradio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haecker-felix/gradio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haecker-felix in #98: I'm sorry i but i cannot reproduce. This station is working for me fine. Make sure your gstreamer setup is correct. "}],"action":{"name":"View Issue","url":"https://github.com/haecker-felix/gradio/issues/98#issuecomment-261719339"}}}
    
    The system is fresh, new setup (Ubuntu 16.04.1 / 32bit).
      Which component is needed of Gstreamer ?
      The libgstreamer is installed...
      GRadio invariably works wrongly ... :(
    Thank youcsola48

**Comment by csola48** [comment]
GRadio from terminal:
~$ gradio
** Message: Gradio.vala:122: Starting Gradio version 4.0.1!
** Message: MPRIS.vala:21: Successfully initialized MPRIS session.
** Message: Library.vala:90: Reading library data from: /home/csola48/.local/share/gradio/library.gradio
** Message: Library.vala:109: No gradio library found. 
** Message: Library.vala:115: Successfully imported library
** Message: MainWindow.vala:66: Desktop session is: ubuntu
** Message: Util.vala:128: Loaded /usr/share/gradio/style/style.css

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

(gradio:8859): Gtk-CRITICAL **: gtk_image_set_from_pixbuf: assertion 'GTK_IS_IMAGE (image)' failed

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null
A GStreamer telepítésből hiányzik egy bővítmény.
** (gradio:8859): WARNING **: MPRIS.vala:150: MPRIS metadata is null

Pls. help...

**Comment by haecker-felix** [comment]
`sudo apt-get install libxvidcore4 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-fluendo-mp3 gstreamer1.0-libav `

This should help.

**Comment by csola48** [comment]
Nothing...
már a legújabb verzió = already the newest version
The all suggested packet of them was installed already....
Terminal:
~$ sudo apt-get install libxvidcore4 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-fluendo-mp3 gstreamer1.0-libav
[sudo] csola48 jelszava: 
Csomaglisták olvasása... Kész
Függőségi fa építése       
Állapotinformációk olvasása... Kész
gstreamer1.0-fluendo-mp3 már a legújabb verzió (0.10.32.debian-1).
libxvidcore4 már a legújabb verzió (2:1.3.4-1).
gstreamer1.0-alsa már a legújabb verzió (1.8.2-1ubuntu0.1).
gstreamer1.0-plugins-base már a legújabb verzió (1.8.2-1ubuntu0.1).
gstreamer1.0-plugins-good már a legújabb verzió (1.8.2-1ubuntu0.1).
gstreamer1.0-libav már a legújabb verzió (1.8.2-1~ubuntu1).
gstreamer1.0-plugins-bad már a legújabb verzió (1.8.2-1ubuntu0.2).
gstreamer1.0-plugins-ugly már a legújabb verzió (1.8.2-1ubuntu0.1).

**Comment by csola48** [comment]
+2 image
![kepmentes_014](https://cloud.githubusercontent.com/assets/893186/20462721/10e6435e-af25-11e6-9573-118b031f027c.png)


![kepmentes_013](https://cloud.githubusercontent.com/assets/893186/20462706/b6fbde44-af24-11e6-82e3-01cdd6408a75.png)
